<a href="https://colab.research.google.com/github/emmanresu/Thesis-Keras/blob/feature%2Fprototype/prototype/requests_prototype.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Request data from endpoint

In [1]:
import json
import requests
import pandas as pd
from datetime import date
from numpy import where

In [ ]:
curr_year = date.today().year
year_stock = [str(i) for i in range(2000, curr_year + 1)]
year_part1 = ['10', '11', '12', '13', '14', '15', '16', '17', '18', '19']
year_part2 = [str(i - 2010) for i in range(2010, curr_year + 1)]
month = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11']

query total, commercial, household, nfa stock

In [ ]:
# rice stock inventory (monthly total stocks inventory by sector)
url = 'https://openstat.psa.gov.ph/PXWeb/api/v1/en/DB/2E/CS/0032E4ECNV0.px'

# 2. Define your query payload
payload = {
    "query": [
        {
            "code": "Sector",
            "selection": {"filter": "item", "values": ["0", "1", "2", "3"]},
        },  # Rice total, commercial, household, and nfa stocks
        {
            "code": "Year",
            "selection": {"filter": "item", "values": year_stock},
        },  # Years
        {
            "code": "Month",
            "selection": {
                "filter": "item",
                "values": month,
            },
        },  # Jan - Dec
    ],
    "response": {"format": "json"},
}

headers = {"Content-Type": "application/json"}

print("[Sending request to API]")

try:
    # 3. Make the POST request
    response = requests.post(url, data=json.dumps(payload), headers=headers)

    if response.status_code == 200:
        response.encoding = "utf-8-sig"

        data = response.json()

        # 4. Save the data to a local JSON file
        output_filename = "stocks_inventory_data.json"

        with open(output_filename, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=4, ensure_ascii=False)

        print(f"[Successfully retrieved data. Saved locally as: '{output_filename}']")

    else:
        print(f"API Error {response.status_code}: {response.text}")

    # df = pd.json_normalize(response.json())
    # print_this = df.to_string()
    # print_this = print_this.replace("\\n", "\n")
    # print(print_this)
except requests.exceptions.RequestException as e:
    print(f"An error occurred while connecting to the API: {e}")

[Sending request to API]
[Successfully retrieved data. Saved locally as: 'stocks_inventory_data.json']

query wholesale rice price 2000 - 2009

notes: needs editing

In [ ]:
# rice whole sale price 2000-2010
url = 'https://openstat.psa.gov.ph/PXWeb/api/v1/en/DB/2M/WS/0012M4AWP01.px'

# 2. Define your query payload
payload = {
    "query": [
        {
            "code": "Region Province",
            "selection": {"filter": "item", "values": ["00"]},
        },  # 00 -> Philippines
        {
            "code": "Commodity",
            "selection": {"filter": "item", "values": ["2", "3"]},
        },  # 2 -> well-milled rice | 3 -> regular-milled rice
        {
            "code": "Year",
            "selection": {"filter": "item", "values": year_part1},
        },  # Years [10 -> 2000 | 11 -> 2001 | 12 -> 2002 ... ]
        {
            "code": "Month",
            "selection": {
                "filter": "item",
                "values": month,
            },
        },  # Jan - Dec
    ],
    "response": {"format": "json"},
}

headers = {"Content-Type": "application/json"}

print("[Sending request to API]")

try:
    # 3. Make the POST request
    response = requests.post(url, data=json.dumps(payload), headers=headers)

    if response.status_code == 200:
        response.encoding = "utf-8-sig"

        data = response.json()

        # 4. Save the data to a local JSON file
        output_filename = "stocks_inventory_data.json"

        with open(output_filename, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=4, ensure_ascii=False)

        print(f"[Successfully retrieved data. Saved locally as: '{output_filename}']")

    else:
        print(f"API Error {response.status_code}: {response.text}")

    df = pd.json_normalize(response.json())
    print_this = df.to_string()
    print_this = print_this.replace("\\n", "\n")
    print(print_this)
except requests.exceptions.RequestException as e:
    print(f"An error occurred while connecting to the API: {e}")

[Sending request to API]
[Successfully retrieved data. Saved locally as: 'stocks_inventory_data.json']
                                                                                                                                                                                                                                                                                                                                                                                           columns                                                                                                   comments                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           data
0  [{'code': 'Region Province', 'text': 'Region Province', 'type': 'd'}, {'code': 'Commodity', 'text': 'Commodity', 'type': 'd'}, {'code': 'Year', 'text': 'Year', 'type': 't'}, {'code': 'Month', 'text': 'Month', 'type': 'd'}, {'code': 'Cereals: Wholesale Selling Prices of Agricultural Commodities', 'text': 'Cereals: Wholesale Selling Prices of Agricultural Commodities', 'type': 'c'}]  [{'variable': 'Month', 'value': '11', 'comment': 'w/o MM and Eastern Samar
(No report yet) 02-06-15
'}]  [{'key': ['00', '2', '10', '0'], 'values': ['17.38']}, {'key': ['00', '2', '10', '1'], 'values': ['17.57']}, {'key': ['00', '2', '10', '2'], 'values': ['17.64']}, {'key': ['00', '2', '10', '3'], 'values': ['17.62']}, {'key': ['00', '2', '10', '4'], 'values': ['17.75']}, {'key': ['00', '2', '10', '5'], 'values': ['17.86']}, {'key': ['00', '2', '10', '6'], 'values': ['18.13']}, {'key': ['00', '2', '10', '7'], 'values': ['18.31']}, {'key': ['00', '2', '10', '8'], 'values': ['18.16']}, {'key': ['00', '2', '10', '9'], 'values': ['17.74']}, {'key': ['00', '2', '10', '10'], 'values': ['17.56']}, {'key': ['00', '2', '10', '11'], 'values': ['17.51']}, {'key': ['00', '2', '11', '0'], 'values': ['17.59']}, {'key': ['00', '2', '11', '1'], 'values': ['17.54']}, {'key': ['00', '2', '11', '2'], 'values': ['17.55']}, {'key': ['00', '2', '11', '3'], 'values': ['17.51']}, {'key': ['00', '2', '11', '4'], 'values': ['17.48']}, {'key': ['00', '2', '11', '5'], 'values': ['17.65']}, {'key': ['00', '2', '11', '6'], 'values': ['17.89']}, {'key': ['00', '2', '11', '7'], 'values': ['18.00']}, {'key': ['00', '2', '11', '8'], 'values': ['17.78']}, {'key': ['00', '2', '11', '9'], 'values': ['17.46']}, {'key': ['00', '2', '11', '10'], 'values': ['17.37']}, {'key': ['00', '2', '11', '11'], 'values': ['17.44']}, {'key': ['00', '2', '12', '0'], 'values': ['17.78']}, {'key': ['00', '2', '12', '1'], 'values': ['17.86']}, {'key': ['00', '2', '12', '2'], 'values': ['17.99']}, {'key': ['00', '2', '12', '3'], 'values': ['17.66']}, {'key': ['00', '2', '12', '4'], 'values': ['17.75']}, {'key': ['00', '2', '12', '5'], 'values': ['18.04']}, {'key': ['00', '2', '12', '6'], 'values': ['18.55']}, {'key': ['00', '2', '12', '7'], 'values': ['19.31']}, {'key': ['00', '2', '12', '8'], 'values': ['19.28']}, {'key': ['00', '2', '12', '9'], 'values': ['18.37']}, {'key': ['00', '2', '12', '10'], 'values': ['17.98']}, {'key': ['00', '2', '12', '11'], 'values': ['17.90']}, {'key': ['00', '2', '13', '0'], 'values': ['17.92']}, {'key': ['00', '2', '13', '1'], 'values': ['17.94']}, {'key': ['00', '2', '13', '2'], 'values': ['17.82']}, {'key': ['00', '2', '13', '3'], 'values': ['18.05']}, {'key': ['00', '2', '13', '4'], 'values': ['18.33']}, {'key': ['00', '2', '13', '5'], 'values': ['18.67']}, {'key': ['00', '2', '13', '6'], 'values': ['19.01']}, {'key': ['00', '2', '13', '7'], 'values': ['19.17']}, {'key': ['00', '2', '13', '8'], 'values': ['18.63']}, {'key': ['00', '2', '13', '9'], 'values': ['18.21']}, {'key': ['00', '2', '13', '10'], 'values': ['17.93']}, {'key': ['00', '2', '13', '11'], 'values': ['17.96']}, {'key': ['00', '2', '14', '0'], 'values': ['18.13']}, {'key': ['00', '2', '14', '1'], 'values': ['18.19']}, {'key': ['00', '2', '14', '2'], 'values': ['18.62']}, {'key': ['00', '2', '14', '3'], 'values': ['18.87']}, {'key': ['00', '2', '14', '4'], 'values': ['19.01']}, {'key': ['00', '2', '14', '5'], 'values': ['19.48']}, {'key': ['00', '2', '14', '6'], 'values': ['20.08']}, {'key': ['00', '2', '14', '7'], 'values': ['20.24']}, {'key': ['00', '2', '14', '8'], 'values': ['19.74']}, {'key': ['00', '2', '14', '9'], 'values': ['19.00']}, {'key': ['00', '2', '14', '10'], 'values': ['18.92']}, {'key': ['00', '2', '14', '11'], 'values': ['19.14']}, {'key': ['00', '2', '15', '0'], 'values': ['19.42']}, {'key': ['00', '2', '15', '1'], 'values': ['19.64']}, {'key': ['00', '2', '15', '2'], 'values': ['20.07']}, {'key': ['00', '2', '15', '3'], 'values': ['20.90']}, {'key': ['00', '2', '15', '4'], 'values': ['21.29']}, {'key': ['00', '2', '15', '5'], 'values': ['21.52']}, {'key': ['00', '2', '15', '6'], 'values': ['21.92']}, {'key': ['00', '2', '15', '7'], 'values': ['22.20']}, {'key': ['00', '2', '15', '8'], 'values': ['21.68']}, {'key': ['00', '2', '15', '9'], 'values': ['21.01']}, {'key': ['00', '2', '15', '10'], 'values': ['20.70']}, {'key': ['00', '2', '15', '11'], 'values': ['20.76']}, {'key': ['00', '2', '16', '0'], 'values': ['20.88']}, {'key': ['00', '2', '16', '1'], 'values': ['21.13']}, {'key': ['00', '2', '16', '2'], 'values': ['21.41']}, {'key': ['00', '2', '16', '3'], 'values': ['21.49']}, {'key': ['00', '2', '16', '4'], 'values': ['21.63']}, {'key': ['00', '2', '16', '5'], 'values': ['21.71']}, {'key': ['00', '2', '16', '6'], 'values': ['21.86']}, {'key': ['00', '2', '16', '7'], 'values': ['21.79']}, {'key': ['00', '2', '16', '8'], 'values': ['21.40']}, {'key': ['00', '2', '16', '9'], 'values': ['21.14']}, {'key': ['00', '2', '16', '10'], 'values': ['21.07']}, {'key': ['00', '2', '16', '11'], 'values': ['21.17']}, {'key': ['00', '2', '17', '0'], 'values': ['21.39']}, {'key': ['00', '2', '17', '1'], 'values': ['21.59']}, {'key': ['00', '2', '17', '2'], 'values': ['22.07']}, {'key': ['00', '2', '17', '3'], 'values': ['22.18']}, {'key': ['00', '2', '17', '4'], 'values': ['22.27']}, {'key': ['00', '2', '17', '5'], 'values': ['22.41']}, {'key': ['00', '2', '17', '6'], 'values': ['22.73']}, {'key': ['00', '2', '17', '7'], 'values': ['23.10']}, {'key': ['00', '2', '17', '8'], 'values': ['23.53']}, {'key': ['00', '2', '17', '9'], 'values': ['23.34']}, {'key': ['00', '2', '17', '10'], 'values': ['23.18']}, {'key': ['00', '2', '17', '11'], 'values': ['23.31']}, {'key': ['00', '2', '18', '0'], 'values': ['23.67']}, {'key': ['00', '2', '18', '1'], 'values': ['24.00']}, {'key': ['00', '2', '18', '2'], 'values': ['25.60']}, {'key': ['00', '2', '18', '3'], 'values': ['30.18']}, ...]

query wholesale price 2010 - current year

notes: improve how to access year

In [ ]:
# rice whole sale price 2000-2010
url = 'https://openstat.psa.gov.ph/PXWeb/api/v1/en/DB/2M/NWSNEW/0052M4AWB01.px'

# 2. Define your query payload
payload = {
    "query": [
        { "code": "Geolocation", "selection": {"filter": "item", "values": ["0"]}},
        { "code": "Commodity", "selection": {"filter": "item", "values": ["2", "3"]}},
        { "code": "Year", "selection": {"filter": "item", "values": year_part2}},
        { "code": "Period", "selection": { "filter": "item", "values": month}},  # Jan - Dec
    ],
    "response": {"format": "json"},
}

headers = {"Content-Type": "application/json"}

print("[Sending request to API]")

try:
    # 3. Make the POST request
    response = requests.post(url, data=json.dumps(payload), headers=headers)

    if response.status_code == 200:
        response.encoding = "utf-8-sig"

        data = response.json()

        # 4. Save the data to a local JSON file
        output_filename = "stocks_inventory_data.json"

        with open(output_filename, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=4, ensure_ascii=False)

        print(f"[Successfully retrieved data. Saved locally as: '{output_filename}']")

    else:
        print(f"API Error {response.status_code}: {response.text}")

    df = pd.json_normalize(response.json())
    print_this = df.to_string()
    print_this = print_this.replace("\\n", "\n")
    print(print_this)
except requests.exceptions.RequestException as e:
    print(f"An error occurred while connecting to the API: {e}")

[Sending request to API]
[Successfully retrieved data. Saved locally as: 'stocks_inventory_data.json']
                                                                                                                                                                                                                                                                                                                                                                                                                                                           columns comments                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   data
0  [{'code': 'Geolocation', 'text': 'Geolocation', 'type': 'd'}, {'code': 'Commodity', 'text': 'Commodity', 'type': 'd'}, {'code': 'Year', 'text': 'Year', 'type': 't'}, {'code': 'Period', 'text': 'Period', 'type': 'd'}, {'code': 'Wholesale Prices of Selected Agricultural Commodities by Commodity, Geolocation, year and period', 'text': 'Wholesale Prices of Selected Agricultural Commodities by Commodity, Geolocation, year and period', 'type': 'c'}]       []  [{'key': ['0', '2', '0', '0'], 'values': ['31.27']}, {'key': ['0', '2', '0', '1'], 'values': ['31.73']}, {'key': ['0', '2', '0', '2'], 'values': ['31.99']}, {'key': ['0', '2', '0', '3'], 'values': ['31.58']}, {'key': ['0', '2', '0', '4'], 'values': ['31.38']}, {'key': ['0', '2', '0', '5'], 'values': ['31.60']}, {'key': ['0', '2', '0', '6'], 'values': ['31.72']}, {'key': ['0', '2', '0', '7'], 'values': ['31.69']}, {'key': ['0', '2', '0', '8'], 'values': ['31.55']}, {'key': ['0', '2', '0', '9'], 'values': ['31.12']}, {'key': ['0', '2', '0', '10'], 'values': ['30.92']}, {'key': ['0', '2', '0', '11'], 'values': ['31.17']}, {'key': ['0', '2', '1', '0'], 'values': ['31.54']}, {'key': ['0', '2', '1', '1'], 'values': ['31.90']}, {'key': ['0', '2', '1', '2'], 'values': ['31.90']}, {'key': ['0', '2', '1', '3'], 'values': ['32.02']}, {'key': ['0', '2', '1', '4'], 'values': ['32.11']}, {'key': ['0', '2', '1', '5'], 'values': ['32.17']}, {'key': ['0', '2', '1', '6'], 'values': ['32.19']}, {'key': ['0', '2', '1', '7'], 'values': ['32.22']}, {'key': ['0', '2', '1', '8'], 'values': ['32.15']}, {'key': ['0', '2', '1', '9'], 'values': ['32.09']}, {'key': ['0', '2', '1', '10'], 'values': ['32.15']}, {'key': ['0', '2', '1', '11'], 'values': ['32.28']}, {'key': ['0', '2', '2', '0'], 'values': ['32.54']}, {'key': ['0', '2', '2', '1'], 'values': ['32.38']}, {'key': ['0', '2', '2', '2'], 'values': ['32.59']}, {'key': ['0', '2', '2', '3'], 'values': ['32.70']}, {'key': ['0', '2', '2', '4'], 'values': ['32.78']}, {'key': ['0', '2', '2', '5'], 'values': ['32.90']}, {'key': ['0', '2', '2', '6'], 'values': ['33.19']}, {'key': ['0', '2', '2', '7'], 'values': ['33.26']}, {'key': ['0', '2', '2', '8'], 'values': ['33.04']}, {'key': ['0', '2', '2', '9'], 'values': ['32.75']}, {'key': ['0', '2', '2', '10'], 'values': ['32.75']}, {'key': ['0', '2', '2', '11'], 'values': ['32.73']}, {'key': ['0', '2', '3', '0'], 'values': ['32.77']}, {'key': ['0', '2', '3', '1'], 'values': ['32.78']}, {'key': ['0', '2', '3', '2'], 'values': ['32.79']}, {'key': ['0', '2', '3', '3'], 'values': ['32.72']}, {'key': ['0', '2', '3', '4'], 'values': ['32.80']}, {'key': ['0', '2', '3', '5'], 'values': ['33.18']}, {'key': ['0', '2', '3', '6'], 'values': ['34.51']}, {'key': ['0', '2', '3', '7'], 'values': ['36.01']}, {'key': ['0', '2', '3', '8'], 'values': ['37.02']}, {'key': ['0', '2', '3', '9'], 'values': ['36.22']}, {'key': ['0', '2', '3', '10'], 'values': ['36.37']}, {'key': ['0', '2', '3', '11'], 'values': ['36.78']}, {'key': ['0', '2', '4', '0'], 'values': ['37.12']}, {'key': ['0', '2', '4', '1'], 'values': ['37.69']}, {'key': ['0', '2', '4', '2'], 'values': ['38.56']}, {'key': ['0', '2', '4', '3'], 'values': ['38.94']}, {'key': ['0', '2', '4', '4'], 'values': ['39.44']}, {'key': ['0', '2', '4', '5'], 'values': ['40.07']}, {'key': ['0', '2', '4', '6'], 'values': ['41.01']}, {'key': ['0', '2', '4', '7'], 'values': ['41.38']}, {'key': ['0', '2', '4', '8'], 'values': ['41.12']}, {'key': ['0', '2', '4', '9'], 'values': ['40.62']}, {'key': ['0', '2', '4', '10'], 'values': ['40.05']}, {'key': ['0', '2', '4', '11'], 'values': ['39.96']}, {'key': ['0', '2', '5', '0'], 'values': ['39.13']}, {'key': ['0', '2', '5', '1'], 'values': ['38.66']}, {'key': ['0', '2', '5', '2'], 'values': ['38.23']}, {'key': ['0', '2', '5', '3'], 'values': ['38.24']}, {'key': ['0', '2', '5', '4'], 'values': ['38.73']}, {'key': ['0', '2', '5', '5'], 'values': ['38.12']}, {'key': ['0', '2', '5', '6'], 'values': ['38.17']}, {'key': ['0', '2', '5', '7'], 'values': ['38.34']}, {'key': ['0', '2', '5', '8'], 'values': ['38.10']}, {'key': ['0', '2', '5', '9'], 'values': ['38.05']}, {'key': ['0', '2', '5', '10'], 'values': ['37.27']}, {'key': ['0', '2', '5', '11'], 'values': ['37.55']}, {'key': ['0', '2', '6', '0'], 'values': ['37.35']}, {'key': ['0', '2', '6', '1'], 'values': ['37.62']}, {'key': ['0', '2', '6', '2'], 'values': ['37.82']}, {'key': ['0', '2', '6', '3'], 'values': ['37.81']}, {'key': ['0', '2', '6', '4'], 'values': ['37.87']}, {'key': ['0', '2', '6', '5'], 'values': ['38.32']}, {'key': ['0', '2', '6', '6'], 'values': ['38.57']}, {'key': ['0', '2', '6', '7'], 'values': ['38.42']}, {'key': ['0', '2', '6', '8'], 'values': ['38.66']}, {'key': ['0', '2', '6', '9'], 'values': ['37.93']}, {'key': ['0', '2', '6', '10'], 'values': ['37.64']}, {'key': ['0', '2', '6', '11'], 'values': ['37.86']}, {'key': ['0', '2', '7', '0'], 'values': ['38.27']}, {'key': ['0', '2', '7', '1'], 'values': ['38.54']}, {'key': ['0', '2', '7', '2'], 'values': ['38.47']}, {'key': ['0', '2', '7', '3'], 'values': ['38.65']}, {'key': ['0', '2', '7', '4'], 'values': ['38.71']}, {'key': ['0', '2', '7', '5'], 'values': ['38.84']}, {'key': ['0', '2', '7', '6'], 'values': ['39.04']}, {'key': ['0', '2', '7', '7'], 'values': ['39.28']}, {'key': ['0', '2', '7', '8'], 'values': ['39.23']}, {'key': ['0', '2', '7', '9'], 'values': ['39.14']}, {'key': ['0', '2', '7', '10'], 'values': ['39.41']}, {'key': ['0', '2', '7', '11'], 'values': ['39.25']}, {'key': ['0', '2', '8', '0'], 'values': ['39.74']}, {'key': ['0', '2', '8', '1'], 'values': ['40.58']}, {'key': ['0', '2', '8', '2'], 'values': ['40.96']}, {'key': ['0', '2', '8', '3'], 'values': ['41.16']}, ...]

query retail price 2000 - 2010

In [ ]:
# rice whole sale price 2000-2010
url = 'https://openstat.psa.gov.ph/PXWeb/api/v1/en/DB/2M/RP/0042M4ARP01.px'

# curr_year = date.today().year
# years = [str(i) for i in range(2000, curr_year + 1)]
year = [str(i) for i in range(20)]

# 2. Define your query payload
payload = {
    "query": [
        {
            "code": "Geolocation",
            "selection": {"filter": "item", "values": ["00"]},
        },  # Philippines
        {
            "code": "Commodity",
            "selection": {"filter": "item", "values": ["2", "3"]},
        },  # well milled and regular price
        {
            "code": "Year",
            "selection": {"filter": "item", "values": year_part1},
        },  # Years [10 = 2010 | 11 = 2011 | 12 = 2012 ... ]
        {
            "code": "Period",
            "selection": {
                "filter": "item",
                "values": ["0", "1", "2", "3", "4", "5", "6", "7",
                           "8", "9", "10", "11"],
            },
        },  # Jan - Dec
    ],
    "response": {"format": "json"},
}

headers = {"Content-Type": "application/json"}

print("[Sending request to API]")

try:
    # 3. Make the POST request
    response = requests.post(url, data=json.dumps(payload), headers=headers)

    if response.status_code == 200:
        response.encoding = "utf-8-sig"

        data = response.json()

        # 4. Save the data to a local JSON file
        output_filename = "stocks_inventory_data.json"

        with open(output_filename, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=4, ensure_ascii=False)

        print(f"[Successfully retrieved data. Saved locally as: '{output_filename}']")

    else:
        print(f"API Error {response.status_code}: {response.text}")

    df = pd.json_normalize(response.json())
    print_this = df.to_string()
    print_this = print_this.replace("\\n", "\n")
    print(print_this)
except requests.exceptions.RequestException as e:
    print(f"An error occurred while connecting to the API: {e}")

[Sending request to API]
[Successfully retrieved data. Saved locally as: 'stocks_inventory_data.json']
                                                                                                                                                                                                                                                                                                                                                                                             columns                                                                                                    comments                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           data
0  [{'code': 'Geolocation', 'text': 'Geolocation', 'type': 'd'}, {'code': 'Commodity', 'text': 'Commodity', 'type': 'd'}, {'code': 'Year', 'text': 'Year', 'type': 't'}, {'code': 'Period', 'text': 'Period', 'type': 'd'}, {'code': 'Cereals: Retail Prices by Geolocation, Commodity, Year and Period', 'text': 'Cereals: Retail Prices by Geolocation, Commodity, Year and Period', 'type': 'c'}]  [{'variable': 'Period', 'value': '11', 'comment': 'w/o MM and Eastern Samar
(No report yet) 02-06-15
'}]  [{'key': ['00', '2', '10', '0'], 'values': ['19.00']}, {'key': ['00', '2', '10', '1'], 'values': ['19.12']}, {'key': ['00', '2', '10', '2'], 'values': ['19.22']}, {'key': ['00', '2', '10', '3'], 'values': ['19.21']}, {'key': ['00', '2', '10', '4'], 'values': ['19.27']}, {'key': ['00', '2', '10', '5'], 'values': ['19.38']}, {'key': ['00', '2', '10', '6'], 'values': ['19.74']}, {'key': ['00', '2', '10', '7'], 'values': ['19.99']}, {'key': ['00', '2', '10', '8'], 'values': ['19.96']}, {'key': ['00', '2', '10', '9'], 'values': ['19.64']}, {'key': ['00', '2', '10', '10'], 'values': ['19.48']}, {'key': ['00', '2', '10', '11'], 'values': ['19.37']}, {'key': ['00', '2', '11', '0'], 'values': ['19.37']}, {'key': ['00', '2', '11', '1'], 'values': ['19.36']}, {'key': ['00', '2', '11', '2'], 'values': ['19.36']}, {'key': ['00', '2', '11', '3'], 'values': ['19.29']}, {'key': ['00', '2', '11', '4'], 'values': ['19.33']}, {'key': ['00', '2', '11', '5'], 'values': ['19.45']}, {'key': ['00', '2', '11', '6'], 'values': ['19.64']}, {'key': ['00', '2', '11', '7'], 'values': ['19.68']}, {'key': ['00', '2', '11', '8'], 'values': ['19.57']}, {'key': ['00', '2', '11', '9'], 'values': ['19.47']}, {'key': ['00', '2', '11', '10'], 'values': ['19.30']}, {'key': ['00', '2', '11', '11'], 'values': ['19.31']}, {'key': ['00', '2', '12', '0'], 'values': ['19.33']}, {'key': ['00', '2', '12', '1'], 'values': ['19.40']}, {'key': ['00', '2', '12', '2'], 'values': ['19.41']}, {'key': ['00', '2', '12', '3'], 'values': ['19.42']}, {'key': ['00', '2', '12', '4'], 'values': ['19.49']}, {'key': ['00', '2', '12', '5'], 'values': ['19.69']}, {'key': ['00', '2', '12', '6'], 'values': ['20.16']}, {'key': ['00', '2', '12', '7'], 'values': ['21.00']}, {'key': ['00', '2', '12', '8'], 'values': ['21.31']}, {'key': ['00', '2', '12', '9'], 'values': ['20.55']}, {'key': ['00', '2', '12', '10'], 'values': ['20.02']}, {'key': ['00', '2', '12', '11'], 'values': ['19.94']}, {'key': ['00', '2', '13', '0'], 'values': ['19.92']}, {'key': ['00', '2', '13', '1'], 'values': ['19.85']}, {'key': ['00', '2', '13', '2'], 'values': ['19.86']}, {'key': ['00', '2', '13', '3'], 'values': ['19.92']}, {'key': ['00', '2', '13', '4'], 'values': ['20.13']}, {'key': ['00', '2', '13', '5'], 'values': ['20.44']}, {'key': ['00', '2', '13', '6'], 'values': ['20.70']}, {'key': ['00', '2', '13', '7'], 'values': ['20.89']}, {'key': ['00', '2', '13', '8'], 'values': ['20.57']}, {'key': ['00', '2', '13', '9'], 'values': ['20.20']}, {'key': ['00', '2', '13', '10'], 'values': ['19.95']}, {'key': ['00', '2', '13', '11'], 'values': ['19.97']}, {'key': ['00', '2', '14', '0'], 'values': ['20.05']}, {'key': ['00', '2', '14', '1'], 'values': ['20.06']}, {'key': ['00', '2', '14', '2'], 'values': ['20.46']}, {'key': ['00', '2', '14', '3'], 'values': ['20.71']}, {'key': ['00', '2', '14', '4'], 'values': ['20.90']}, {'key': ['00', '2', '14', '5'], 'values': ['21.17']}, {'key': ['00', '2', '14', '6'], 'values': ['21.75']}, {'key': ['00', '2', '14', '7'], 'values': ['22.02']}, {'key': ['00', '2', '14', '8'], 'values': ['21.82']}, {'key': ['00', '2', '14', '9'], 'values': ['21.24']}, {'key': ['00', '2', '14', '10'], 'values': ['21.07']}, {'key': ['00', '2', '14', '11'], 'values': ['21.23']}, {'key': ['00', '2', '15', '0'], 'values': ['21.51']}, {'key': ['00', '2', '15', '1'], 'values': ['21.56']}, {'key': ['00', '2', '15', '2'], 'values': ['21.83']}, {'key': ['00', '2', '15', '3'], 'values': ['22.62']}, {'key': ['00', '2', '15', '4'], 'values': ['23.12']}, {'key': ['00', '2', '15', '5'], 'values': ['23.27']}, {'key': ['00', '2', '15', '6'], 'values': ['23.60']}, {'key': ['00', '2', '15', '7'], 'values': ['23.91']}, {'key': ['00', '2', '15', '8'], 'values': ['23.62']}, {'key': ['00', '2', '15', '9'], 'values': ['23.27']}, {'key': ['00', '2', '15', '10'], 'values': ['23.12']}, {'key': ['00', '2', '15', '11'], 'values': ['23.15']}, {'key': ['00', '2', '16', '0'], 'values': ['23.23']}, {'key': ['00', '2', '16', '1'], 'values': ['23.36']}, {'key': ['00', '2', '16', '2'], 'values': ['23.48']}, {'key': ['00', '2', '16', '3'], 'values': ['23.50']}, {'key': ['00', '2', '16', '4'], 'values': ['23.59']}, {'key': ['00', '2', '16', '5'], 'values': ['23.69']}, {'key': ['00', '2', '16', '6'], 'values': ['23.78']}, {'key': ['00', '2', '16', '7'], 'values': ['23.85']}, {'key': ['00', '2', '16', '8'], 'values': ['23.71']}, {'key': ['00', '2', '16', '9'], 'values': ['23.50']}, {'key': ['00', '2', '16', '10'], 'values': ['23.46']}, {'key': ['00', '2', '16', '11'], 'values': ['23.54']}, {'key': ['00', '2', '17', '0'], 'values': ['23.72']}, {'key': ['00', '2', '17', '1'], 'values': ['23.81']}, {'key': ['00', '2', '17', '2'], 'values': ['24.07']}, {'key': ['00', '2', '17', '3'], 'values': ['24.17']}, {'key': ['00', '2', '17', '4'], 'values': ['24.29']}, {'key': ['00', '2', '17', '5'], 'values': ['24.38']}, {'key': ['00', '2', '17', '6'], 'values': ['24.69']}, {'key': ['00', '2', '17', '7'], 'values': ['25.09']}, {'key': ['00', '2', '17', '8'], 'values': ['25.72']}, {'key': ['00', '2', '17', '9'], 'values': ['25.70']}, {'key': ['00', '2', '17', '10'], 'values': ['25.49']}, {'key': ['00', '2', '17', '11'], 'values': ['25.53']}, {'key': ['00', '2', '18', '0'], 'values': ['25.84']}, {'key': ['00', '2', '18', '1'], 'values': ['26.08']}, {'key': ['00', '2', '18', '2'], 'values': ['27.57']}, {'key': ['00', '2', '18', '3'], 'values': ['32.20']}, ...]

query retail price 2010 - present

notes: double check url and the web automation data retrieval

In [ ]:
# rice whole sale price 2000-2010
url = 'https://openstat.psa.gov.ph/PXWeb/api/v1/en/DB/2M/2018NEW/0042M4ARN01.px'

# curr_year = date.today().year
# years = [str(i) for i in range(2000, curr_year + 1)]
year = [str(i) for i in range(20)]

# 2. Define your query payload
payload = {
    "query": [
        {
            "code": "Geolocation",
            "selection": {"filter": "item", "values": ["000000000"]},
        },  # Philippines
        {
            "code": "Commodity",
            "selection": {"filter": "item", "values": ["0", "1"]},
        },  # well milled and regular price
        {
            "code": "Year",
            "selection": {"filter": "item", "values": year_part2},
        },  # Years [up to present]
        {
            "code": "Period",
            "selection": {
                "filter": "item",
                "values": month,
            },
        },  # Jan - Dec
    ],
    "response": {"format": "json"},
}

headers = {"Content-Type": "application/json"}

print("[Sending request to API]")

try:
    # 3. Make the POST request
    response = requests.post(url, data=json.dumps(payload), headers=headers)

    if response.status_code == 200:
        response.encoding = "utf-8-sig"

        data = response.json()

        # 4. Save the data to a local JSON file
        output_filename = "stocks_inventory_data.json"

        with open(output_filename, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=4, ensure_ascii=False)

        print(f"[Successfully retrieved data. Saved locally as: '{output_filename}']")

    else:
        print(f"API Error {response.status_code}: {response.text}")

    df = pd.json_normalize(response.json())
    print_this = df.to_string()
    print_this = print_this.replace("\\n", "\n")
    print(print_this)
except requests.exceptions.RequestException as e:
    print(f"An error occurred while connecting to the API: {e}")

[Sending request to API]
[Successfully retrieved data. Saved locally as: 'stocks_inventory_data.json']
                                                                                                                                                                                                                                                                                                                                             columns comments                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   data
0  [{'code': 'Geolocation', 'text': 'Geolocation', 'type': 'd'}, {'code': 'Commodity', 'text': 'Commodity', 'type': 'd'}, {'code': 'Year', 'text': 'Year', 'type': 't'}, {'code': 'Period', 'text': 'Period', 'type': 'd'}, {'code': 'Retail Prices of Agricultural Commodities', 'text': 'Retail Prices of Agricultural Commodities', 'type': 'c'}]       []  [{'key': ['000000000', '0', '0', '0'], 'values': ['44.77']}, {'key': ['000000000', '0', '0', '1'], 'values': ['45.25']}, {'key': ['000000000', '0', '0', '2'], 'values': ['45.79']}, {'key': ['000000000', '0', '0', '3'], 'values': ['46.01']}, {'key': ['000000000', '0', '0', '4'], 'values': ['46.32']}, {'key': ['000000000', '0', '0', '5'], 'values': ['46.55']}, {'key': ['000000000', '0', '0', '6'], 'values': ['46.99']}, {'key': ['000000000', '0', '0', '7'], 'values': ['48.11']}, {'key': ['000000000', '0', '0', '8'], 'values': ['49.85']}, {'key': ['000000000', '0', '0', '9'], 'values': ['50.21']}, {'key': ['000000000', '0', '0', '10'], 'values': ['49.03']}, {'key': ['000000000', '0', '0', '11'], 'values': ['47.88']}, {'key': ['000000000', '0', '1', '0'], 'values': ['47.23']}, {'key': ['000000000', '0', '1', '1'], 'values': ['46.99']}, {'key': ['000000000', '0', '1', '2'], 'values': ['46.66']}, {'key': ['000000000', '0', '1', '3'], 'values': ['46.22']}, {'key': ['000000000', '0', '1', '4'], 'values': ['45.74']}, {'key': ['000000000', '0', '1', '5'], 'values': ['45.42']}, {'key': ['000000000', '0', '1', '6'], 'values': ['45.05']}, {'key': ['000000000', '0', '1', '7'], 'values': ['44.79']}, {'key': ['000000000', '0', '1', '8'], 'values': ['44.33']}, {'key': ['000000000', '0', '1', '9'], 'values': ['43.88']}, {'key': ['000000000', '0', '1', '10'], 'values': ['43.44']}, {'key': ['000000000', '0', '1', '11'], 'values': ['43.18']}, {'key': ['000000000', '0', '2', '0'], 'values': ['43.02']}, {'key': ['000000000', '0', '2', '1'], 'values': ['42.86']}, {'key': ['000000000', '0', '2', '2'], 'values': ['42.66']}, {'key': ['000000000', '0', '2', '3'], 'values': ['43.61']}, {'key': ['000000000', '0', '2', '4'], 'values': ['43.88']}, {'key': ['000000000', '0', '2', '5'], 'values': ['44.09']}, {'key': ['000000000', '0', '2', '6'], 'values': ['44.16']}, {'key': ['000000000', '0', '2', '7'], 'values': ['44.05']}, {'key': ['000000000', '0', '2', '8'], 'values': ['43.83']}, {'key': ['000000000', '0', '2', '9'], 'values': ['43.46']}, {'key': ['000000000', '0', '2', '10'], 'values': ['43.29']}, {'key': ['000000000', '0', '2', '11'], 'values': ['43.27']}, {'key': ['000000000', '0', '3', '0'], 'values': ['42.84']}, {'key': ['000000000', '0', '3', '1'], 'values': ['42.98']}, {'key': ['000000000', '0', '3', '2'], 'values': ['43.07']}, {'key': ['000000000', '0', '3', '3'], 'values': ['43.13']}, {'key': ['000000000', '0', '3', '4'], 'values': ['43.18']}, {'key': ['000000000', '0', '3', '5'], 'values': ['43.16']}, {'key': ['000000000', '0', '3', '6'], 'values': ['43.27']}, {'key': ['000000000', '0', '3', '7'], 'values': ['43.45']}, {'key': ['000000000', '0', '3', '8'], 'values': ['43.37']}, {'key': ['000000000', '0', '3', '9'], 'values': ['43.27']}, {'key': ['000000000', '0', '3', '10'], 'values': ['43.25']}, {'key': ['000000000', '0', '3', '11'], 'values': ['43.22']}, {'key': ['000000000', '0', '4', '0'], 'values': ['43.13']}, {'key': ['000000000', '0', '4', '1'], 'values': ['43.17']}, {'key': ['000000000', '0', '4', '2'], 'values': ['43.21']}, {'key': ['000000000', '0', '4', '3'], 'values': ['43.31']}, {'key': ['000000000', '0', '4', '4'], 'values': ['43.42']}, {'key': ['000000000', '0', '4', '5'], 'values': ['43.62']}, {'key': ['000000000', '0', '4', '6'], 'values': ['43.72']}, {'key': ['000000000', '0', '4', '7'], 'values': ['43.88']}, {'key': ['000000000', '0', '4', '8'], 'values': ['43.80']}, {'key': ['000000000', '0', '4', '9'], 'values': ['43.82']}, {'key': ['000000000', '0', '4', '10'], 'values': ['43.86']}, {'key': ['000000000', '0', '4', '11'], 'values': ['43.98']}, {'key': ['000000000', '0', '5', '0'], 'values': ['43.92']}, {'key': ['000000000', '0', '5', '1'], 'values': ['43.99']}, {'key': ['000000000', '0', '5', '2'], 'values': ['44.23']}, {'key': ['000000000', '0', '5', '3'], 'values': ['44.53']}, {'key': ['000000000', '0', '5', '4'], 'values': ['44.78']}, {'key': ['000000000', '0', '5', '5'], 'values': ['44.99']}, {'key': ['000000000', '0', '5', '6'], 'values': ['45.32']}, {'key': ['000000000', '0', '5', '7'], 'values': ['47.65']}, {'key': ['000000000', '0', '5', '8'], 'values': ['52.69']}, {'key': ['000000000', '0', '5', '9'], 'values': ['50.99']}, {'key': ['000000000', '0', '5', '10'], 'values': ['51.99']}, {'key': ['000000000', '0', '5', '11'], 'values': ['53.82']}, {'key': ['000000000', '0', '6', '0'], 'values': ['54.91']}, {'key': ['000000000', '0', '6', '1'], 'values': ['55.93']}, {'key': ['000000000', '0', '6', '2'], 'values': ['56.44']}, {'key': ['000000000', '0', '6', '3'], 'values': ['56.42']}, {'key': ['000000000', '0', '6', '4'], 'values': ['56.06']}, {'key': ['000000000', '0', '6', '5'], 'values': ['55.96']}, {'key': ['000000000', '0', '6', '6'], 'values': ['55.85']}, {'key': ['000000000', '0', '6', '7'], 'values': ['55.56']}, {'key': ['000000000', '0', '6', '8'], 'values': ['55.51']}, {'key': ['000000000', '0', '6', '9'], 'values': ['55.28']}, {'key': ['000000000', '0', '6', '10'], 'values': ['54.64']}, {'key': ['000000000', '0', '6', '11'], 'values': ['54.38']}, {'key': ['000000000', '0', '7', '0'], 'values': ['54.14']}, {'key': ['000000000', '0', '7', '1'], 'values': ['53.46']}, {'key': ['000000000', '0', '7', '2'], 'values': ['52.25']}, {'key': ['000000000', '0', '7', '3'], 'values': ['50.54']}, {'key': ['000000000', '0', '7', '4'], 'values': ['49.45']}, {'key': ['000000000', '0', '7', '5'], 'values': ['48.47']}, {'key': ['000000000', '0', '7', '6'], 'values': ['47.60']}, {'key': ['000000000', '0', '7', '7'], 'values': ['46.51']}, {'key': ['000000000', '0', '7', '8'], 'values': ['46.50']}, {'key': ['000000000', '0', '7', '9'], 'values': ['46.49']}, {'key': ['000000000', '0', '7', '10'], 'values': ['46.80']}, {'key': ['000000000', '0', '7', '11'], 'values': ['48.25']}, {'key': ['000000000', '0', '8', '0'], 'values': ['50.05']}, {'key': ['000000000', '0', '8', '1'], 'values': ['52.21']}, {'key': ['000000000', '0', '8', '2'], 'values': ['54.89']}, {'key': ['000000000', '0', '8', '3'], 'values': ['58.07']}, ...]

### Prototype - request function

In [ ]:
def queries(*args):
  query = []
  for i in range(len(args)):
    query.append({'code': f'{args[i][0]}',
                    'selection' : {'filter': 'item',
                    'values': args[i][1]}
    })
  return query

In [ ]:
# url       -> api endpoint url (string)
# queries   -> data to query (2D matrix - example: ['Sector', ['0', '1']], ... )
# checklist -> container to check if data retrieval is success (list)
# filename  -> json filename output (string)

def request_data(url, queries, check_list, filename):
  payload = {
    "query": queries,
    "response": {"format": "json"},
  }
  headers = {"Content-Type": "application/json"}
  try:
    response = requests.post(url, data=json.dumps(payload), headers=headers)

    if response.status_code == 200:
      response.encoding = "utf-8-sig"
      data = response.json()
      output_filename = f"{filename}.json"
      with open(output_filename, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=4, ensure_ascii=False)
      check_list.append("success")
    else:
      check_list.append(f"fail: {response.status_code}")
      # print(f"API Error {response.status_code}: {response.text}")
  except requests.exceptions.RequestException as e:
    check_list.append(f"fail: {e}")
  return response

In [ ]:
# testing the func
url = 'https://openstat.psa.gov.ph/PXWeb/api/v1/en/DB/2E/CS/0032E4ECNV0.px'
sector = ['0', '1', '2', '3']
quers = queries(['Sector', sector],
                ['Year', year_stock],
                ['Month', month])
cl = []
response_stock = request_data(url, quers, cl, "stocks")

### Prototype - Rice stocks

#### Prototype - Rice stocks stage 1 (load data)

In [ ]:
rice_stocks = pd.json_normalize(
    response_stock.json(), record_path=["data"]
)

# Display the cleaned DataFrame
print(rice_stocks)

                key        values
0      [0, 2000, 0]  [2364500.00]
1      [0, 2000, 1]  [2042300.00]
2      [0, 2000, 2]  [1765700.00]
3      [0, 2000, 3]  [1874900.00]
4      [0, 2000, 4]  [2067000.00]
...             ...           ...
1291   [3, 2026, 7]          [..]
1292   [3, 2026, 8]          [..]
1293   [3, 2026, 9]          [..]
1294  [3, 2026, 10]          [..]
1295  [3, 2026, 11]          [..]

[1296 rows x 2 columns]

In [ ]:
rice_stocks.to_csv("test.csv", index=True)

In [ ]:
rice_stocks

                key        values
0      [0, 2000, 0]  [2364500.00]
1      [0, 2000, 1]  [2042300.00]
2      [0, 2000, 2]  [1765700.00]
3      [0, 2000, 3]  [1874900.00]
4      [0, 2000, 4]  [2067000.00]
...             ...           ...
1291   [3, 2026, 7]          [..]
1292   [3, 2026, 8]          [..]
1293   [3, 2026, 9]          [..]
1294  [3, 2026, 10]          [..]
1295  [3, 2026, 11]          [..]

[1296 rows x 2 columns]

In [ ]:
key_split = pd.DataFrame(rice_stocks['key'].to_list(), index=rice_stocks.index)
key_split.columns = ['sector', 'year', 'month']

In [ ]:
convert_mnt = {'0': '01', '1': '02', '2': '03', '3': '04', '4': '05', '5': '06',
                '6': '07', '7': '08', '8': '09', '9': '10', '10': '11', '11': '12'}

key_split['month'] = key_split['month'].map(convert_mnt)

In [ ]:
key_split["date"] = key_split["year"].str.cat(key_split["month"], sep='-')

In [ ]:
key_split = key_split.drop(columns=['year', 'month'])

In [ ]:
key_split

     sector     date
0         0  2000-01
1         0  2000-02
2         0  2000-03
3         0  2000-04
4         0  2000-05
...     ...      ...
1291      3  2026-08
1292      3  2026-09
1293      3  2026-10
1294      3  2026-11
1295      3  2026-12

[1296 rows x 2 columns]

In [ ]:
stocks = pd.DataFrame(rice_stocks['values'].to_list(), index=rice_stocks.index)
stocks.columns = ['stocks']

In [ ]:
key_split = key_split.merge(stocks, on=key_split.index, how='left')
key_split = key_split.drop(columns=['key_0'])

In [ ]:
key_split = key_split.dropna()

In [ ]:
key_split.drop(key_split[key_split['stocks'] == '..'].index, inplace=True)

In [ ]:
key_split

     sector     date      stocks
0         0  2000-01  2364500.00
1         0  2000-02  2042300.00
2         0  2000-03  1765700.00
3         0  2000-04  1874900.00
4         0  2000-05  2067000.00
...     ...      ...         ...
1286      3  2026-03   404386.21
1287      3  2026-04   356607.00
1288      3  2026-05   341346.00
1289      3  2026-06   347943.00
1290      3  2026-07   333029.04

[1276 rows x 3 columns]

#### Prototype - Rice stocks stage 2 (split categories)

In [ ]:
total_stock = key_split.query("sector == '0'")

In [ ]:
total_stock.rename(columns={'stocks': 'total_stock'}, inplace=True)
total_stock = total_stock.drop(columns=['sector'])

/tmp/ipykernel_1458/168397426.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  total_stock.rename(columns={'stocks': 'total_stock'}, inplace=True)

In [ ]:
household_stock = key_split.query("sector == '1'")
household_stock.rename(columns={'stocks': 'stock_household'}, inplace=True)
household_stock = household_stock.drop(columns=['sector'])

/tmp/ipykernel_1458/1107419859.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  household_stock.rename(columns={'stocks': 'stock_household'}, inplace=True)

In [ ]:
total_stock = total_stock.merge(household_stock, how='inner', on='date')

In [ ]:
commercial_stock = key_split.query("sector == '2'")
commercial_stock.rename(columns={'stocks': 'stock_commercial'}, inplace=True)
commercial_stock = commercial_stock.drop(columns=['sector'])
total_stock = total_stock.merge(commercial_stock, how='inner', on='date')

/tmp/ipykernel_1458/2004301664.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  commercial_stock.rename(columns={'stocks': 'stock_commercial'}, inplace=True)

In [ ]:
nfa_stock = key_split.query("sector == '3'")
nfa_stock.rename(columns={'stocks': 'nfa_stock'}, inplace=True)
nfa_stock = nfa_stock.drop(columns=['sector'])
total_stock = total_stock.merge(nfa_stock, how='inner', on='date')

/tmp/ipykernel_1458/916963603.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nfa_stock.rename(columns={'stocks': 'nfa_stock'}, inplace=True)

In [ ]:
total_stock

        date total_stock stock_household stock_commercial  nfa_stock
0    2000-01  2364500.00      1149700.00        488200.00  726600.00
1    2000-02  2042300.00      1009500.00        420600.00  612200.00
2    2000-03  1765700.00       832200.00        381000.00  552500.00
3    2000-04  1874900.00       954400.00        441200.00  479300.00
4    2000-05  2067000.00      1059500.00        509600.00  497900.00
..       ...         ...             ...              ...        ...
314  2026-03  1877328.88       908721.92        564220.75  404386.21
315  2026-04  2378655.18      1195714.21        826333.97  356607.00
316  2026-05  2410587.01      1152685.83        916555.18  341346.00
317  2026-06  2349596.02      1062634.22        939018.80  347943.00
318  2026-07  2509178.82       978913.22       1197236.56  333029.04

[319 rows x 5 columns]

### Prototype - Wholesale prices

#### Prototype - Wholesale prices stage 1 (2000-2009)

In [ ]:
wsprice_1 = pd.json_normalize(
    response.json(), record_path=["data"]
)

# Display the cleaned DataFrame
wsprice_1.head()

              key   values
0  [00, 2, 10, 0]  [17.38]
1  [00, 2, 10, 1]  [17.57]
2  [00, 2, 10, 2]  [17.64]
3  [00, 2, 10, 3]  [17.62]
4  [00, 2, 10, 4]  [17.75]

In [ ]:
wsprice_1.to_csv("wsprice_1.csv", index=True)

In [ ]:
key_split = pd.DataFrame(wsprice_1['key'].to_list(), index=wsprice_1.index)
key_split.columns = ['province', 'commodity', 'year', 'month']

In [ ]:
# 2 -> well-milled rice price
# 3 -> regular milled rice price
key_split["commodity"] = where(key_split["commodity"] == '2', 'milled', 'regular')

In [ ]:
convert_yr = {'10': '2000', '11': '2001', '12': '2002', '13': '2003', '14': '2004', '15': '2005',
              '16': '2006', '17': '2007', '18': '2008', '19': '2009', '20': '2010'}
key_split['year'] = key_split['year'].map(convert_yr)

In [ ]:
# months are zero based [0 -> January ... 11 -> December]
convert_mnt = {'0': '01', '1': '02', '2': '03', '3': '04', '4': '05', '5': '06',
                '6': '07', '7': '08', '8': '09', '9': '10', '10': '11', '11': '12'}

key_split['month'] = key_split['month'].map(convert_mnt)

In [ ]:
key_split["province"] = key_split["year"].str.cat(key_split["month"], sep='-')
key_split = key_split.rename(columns={'province': 'date'})
key_split = key_split.drop(columns=['year', 'month'])

In [ ]:
key_split

        date commodity
0    2000-01    milled
1    2000-02    milled
2    2000-03    milled
3    2000-04    milled
4    2000-05    milled
..       ...       ...
235  2009-08   regular
236  2009-09   regular
237  2009-10   regular
238  2009-11   regular
239  2009-12   regular

[240 rows x 2 columns]

In [ ]:
price = pd.DataFrame(wsprice_1['values'].to_list(), index=wsprice_1.index)
price.columns = ['price']

In [ ]:
key_split = key_split.merge(price, on=key_split.index, how='left')
key_split = key_split.drop(columns=['key_0'])

In [ ]:
key_split

        date commodity  price
0    2000-01    milled  17.38
1    2000-02    milled  17.57
2    2000-03    milled  17.64
3    2000-04    milled  17.62
4    2000-05    milled  17.75
..       ...       ...    ...
235  2009-08   regular  28.12
236  2009-09   regular  27.51
237  2009-10   regular  27.41
238  2009-11   regular  27.71
239  2009-12   regular  27.92

[240 rows x 3 columns]

In [ ]:
wholesale = key_split.query("commodity == 'regular'")

In [ ]:
wholesale.rename(columns={'price': 'regular_wholesale_price'}, inplace=True)
wholesale = wholesale.drop(columns=['commodity'])

/tmp/ipykernel_869/2340502832.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wholesale.rename(columns={'price': 'regular_wholesale_price'}, inplace=True)

In [ ]:
wholesale_temp = key_split.query("commodity == 'milled'")
wholesale_temp.rename(columns={'price': 'milled_wholesale_price'}, inplace=True)
wholesale_temp = wholesale_temp.drop(columns=['commodity'])

/tmp/ipykernel_869/1343147125.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wholesale_temp.rename(columns={'price': 'milled_wholesale_price'}, inplace=True)

In [ ]:
wholesale = wholesale.merge(wholesale_temp, how='inner', on='date')

In [ ]:
wholesale

        date regular_wholesale_price milled_wholesale_price
0    2000-01                   15.65                  17.38
1    2000-02                   15.83                  17.57
2    2000-03                   15.98                  17.64
3    2000-04                   16.05                  17.62
4    2000-05                   16.29                  17.75
..       ...                     ...                    ...
115  2009-08                   28.12                  31.19
116  2009-09                   27.51                  30.62
117  2009-10                   27.41                  30.46
118  2009-11                   27.71                  30.80
119  2009-12                   27.92                  30.81

[120 rows x 3 columns]

#### Prototype - Wholesale prices stage 2 (2010 to current year)

In [ ]:
wsprice_2 = pd.json_normalize(
    response.json(), record_path=["data"]
)

# Display the cleaned DataFrame
wsprice_2.head()

            key   values
0  [0, 2, 0, 0]  [31.27]
1  [0, 2, 0, 1]  [31.73]
2  [0, 2, 0, 2]  [31.99]
3  [0, 2, 0, 3]  [31.58]
4  [0, 2, 0, 4]  [31.38]

In [ ]:
wsprice_2.to_csv("wsprice_2.csv", index=True)

In [ ]:
key_split = pd.DataFrame(wsprice_2['key'].to_list(), index=wsprice_2.index)
key_split.columns = ['province', 'commodity', 'year', 'month']

In [ ]:
# 2 -> well-milled rice price
# 3 -> regular milled rice price
key_split["commodity"] = where(key_split["commodity"] == '2', 'milled', 'regular')

In [ ]:
convert_yr = {str(x): str(x + 2010) for x in range(0, (curr_year + 1 - 2010))}
key_split['year'] = key_split['year'].map(convert_yr)

In [ ]:
# months are zero based [0 -> January ... 11 -> December]
convert_mnt = {'0': '01', '1': '02', '2': '03', '3': '04', '4': '05', '5': '06',
                '6': '07', '7': '08', '8': '09', '9': '10', '10': '11', '11': '12'}

key_split['month'] = key_split['month'].map(convert_mnt)

In [ ]:
key_split["province"] = key_split["year"].str.cat(key_split["month"], sep='-')
key_split = key_split.rename(columns={'province': 'date'})
key_split = key_split.drop(columns=['year', 'month'])

In [ ]:
price = pd.DataFrame(wsprice_2['values'].to_list(), index=wsprice_2.index)
price.columns = ['price']

In [ ]:
key_split = key_split.merge(price, on=key_split.index, how='left')
key_split = key_split.drop(columns=['key_0'])

In [ ]:
key_split

        date commodity  price
0    2010-01    milled  31.27
1    2010-02    milled  31.73
2    2010-03    milled  31.99
3    2010-04    milled  31.58
4    2010-05    milled  31.38
..       ...       ...    ...
403  2026-08   regular     ..
404  2026-09   regular     ..
405  2026-10   regular     ..
406  2026-11   regular     ..
407  2026-12   regular     ..

[408 rows x 3 columns]

In [ ]:
key_split.drop(key_split[key_split['price'] == '..'].index, inplace=True)

In [ ]:
key_split

        date commodity  price
0    2010-01    milled  31.27
1    2010-02    milled  31.73
2    2010-03    milled  31.99
3    2010-04    milled  31.58
4    2010-05    milled  31.38
..       ...       ...    ...
398  2026-03   regular  45.36
399  2026-04   regular  47.46
400  2026-05   regular  46.10
401  2026-06   regular  45.25
402  2026-07   regular  45.00

[398 rows x 3 columns]

In [ ]:
wholesale_2 = key_split.query("commodity == 'regular'")

In [ ]:
wholesale_2.rename(columns={'price': 'regular_wholesale_price'}, inplace=True)
wholesale_2 = wholesale_2.drop(columns=['commodity'])

/tmp/ipykernel_869/978701780.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wholesale_2.rename(columns={'price': 'regular_wholesale_price'}, inplace=True)

In [ ]:
wholesale_2_temp = key_split.query("commodity == 'milled'")
wholesale_2_temp.rename(columns={'price': 'milled_wholesale_price'}, inplace=True)
wholesale_2_temp = wholesale_2_temp.drop(columns=['commodity'])

/tmp/ipykernel_869/1296082271.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wholesale_2_temp.rename(columns={'price': 'milled_wholesale_price'}, inplace=True)

In [ ]:
wholesale_2 = wholesale_2.merge(wholesale_2_temp, how='inner', on='date')

In [ ]:
wholesale_2

        date regular_wholesale_price milled_wholesale_price
0    2010-01                   28.41                  31.27
1    2010-02                   28.89                  31.73
2    2010-03                   28.97                  31.99
3    2010-04                   28.72                  31.58
4    2010-05                   28.34                  31.38
..       ...                     ...                    ...
194  2026-03                   45.36                  50.57
195  2026-04                   47.46                  52.00
196  2026-05                   46.10                  50.18
197  2026-06                   45.25                  49.27
198  2026-07                   45.00                  49.02

[199 rows x 3 columns]

#### Prototype - Wholesale prices stage 3 (combine/concat)

In [ ]:
price = pd.concat([wholesale, wholesale_2], ignore_index=True)

In [ ]:
price

        date regular_wholesale_price milled_wholesale_price
0    2000-01                   15.65                  17.38
1    2000-02                   15.83                  17.57
2    2000-03                   15.98                  17.64
3    2000-04                   16.05                  17.62
4    2000-05                   16.29                  17.75
..       ...                     ...                    ...
314  2026-03                   45.36                  50.57
315  2026-04                   47.46                  52.00
316  2026-05                   46.10                  50.18
317  2026-06                   45.25                  49.27
318  2026-07                   45.00                  49.02

[319 rows x 3 columns]

### Prototype - Retail prices

#### Prototype - Retail prices stage 1 (2000-2010)

In [ ]:
rprice_1 = pd.json_normalize(
    response.json(), record_path=["data"]
)

# Display the cleaned DataFrame
rprice_1.head()

              key   values
0  [00, 2, 10, 0]  [19.00]
1  [00, 2, 10, 1]  [19.12]
2  [00, 2, 10, 2]  [19.22]
3  [00, 2, 10, 3]  [19.21]
4  [00, 2, 10, 4]  [19.27]

In [ ]:
rprice_1.to_csv("rprice_1.csv", index=True)

In [ ]:
key_split = pd.DataFrame(rprice_1['key'].to_list(), index=rprice_1.index)
key_split.columns = ['province', 'commodity', 'year', 'month']

In [ ]:
# 2 -> well-milled rice price
# 3 -> regular milled rice price
key_split["commodity"] = where(key_split["commodity"] == '2', 'milled', 'regular')

In [ ]:
convert_yr = {'10': '2000', '11': '2001', '12': '2002', '13': '2003', '14': '2004', '15': '2005',
              '16': '2006', '17': '2007', '18': '2008', '19': '2009', '20': '2010'}
key_split['year'] = key_split['year'].map(convert_yr)

In [ ]:
# months are zero based [0 -> January ... 11 -> December]
convert_mnt = {'0': '01', '1': '02', '2': '03', '3': '04', '4': '05', '5': '06',
                '6': '07', '7': '08', '8': '09', '9': '10', '10': '11', '11': '12'}

key_split['month'] = key_split['month'].map(convert_mnt)

In [ ]:
key_split["province"] = key_split["year"].str.cat(key_split["month"], sep='-')
key_split = key_split.rename(columns={'province': 'date'})
key_split = key_split.drop(columns=['year', 'month'])

In [ ]:
price = pd.DataFrame(rprice_1['values'].to_list(), index=rprice_1.index)
price.columns = ['price']

In [ ]:
key_split = key_split.merge(price, on=key_split.index, how='left')
key_split = key_split.drop(columns=['key_0'])

In [ ]:
key_split

        date commodity  price
0    2000-01    milled  19.00
1    2000-02    milled  19.12
2    2000-03    milled  19.22
3    2000-04    milled  19.21
4    2000-05    milled  19.27
..       ...       ...    ...
235  2009-08   regular  30.75
236  2009-09   regular  30.33
237  2009-10   regular  29.94
238  2009-11   regular  30.20
239  2009-12   regular  30.30

[240 rows x 3 columns]

In [ ]:
key_split.drop(key_split[key_split['price'] == '..'].index, inplace=True)

In [ ]:
key_split

        date commodity  price
0    2000-01    milled  19.00
1    2000-02    milled  19.12
2    2000-03    milled  19.22
3    2000-04    milled  19.21
4    2000-05    milled  19.27
..       ...       ...    ...
235  2009-08   regular  30.75
236  2009-09   regular  30.33
237  2009-10   regular  29.94
238  2009-11   regular  30.20
239  2009-12   regular  30.30

[240 rows x 3 columns]

In [ ]:
retail = key_split.query("commodity == 'regular'")

In [ ]:
retail.rename(columns={'price': 'regular_retail_price'}, inplace=True)
retail = retail.drop(columns=['commodity'])

/tmp/ipykernel_869/186404501.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  retail.rename(columns={'price': 'regular_retail_price'}, inplace=True)

In [ ]:
retail_temp = key_split.query("commodity == 'milled'")
retail_temp.rename(columns={'price': 'milled_retail_price'}, inplace=True)
retail_temp = retail_temp.drop(columns=['commodity'])

/tmp/ipykernel_869/3743124154.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  retail_temp.rename(columns={'price': 'milled_retail_price'}, inplace=True)

In [ ]:
retail = retail.merge(retail_temp, how='inner', on='date')

In [ ]:
retail

        date regular_retail_price milled_retail_price
0    2000-01                17.05               19.00
1    2000-02                17.20               19.12
2    2000-03                17.32               19.22
3    2000-04                17.38               19.21
4    2000-05                17.45               19.27
..       ...                  ...                 ...
115  2009-08                30.75               34.25
116  2009-09                30.33               33.83
117  2009-10                29.94               33.63
118  2009-11                30.20               33.89
119  2009-12                30.30               33.99

[120 rows x 3 columns]

#### Prototype - Retail prices stage 2 (2010 to current year)

In [ ]:
rprice_2 = pd.json_normalize(
    response.json(), record_path=["data"]
)

# Display the cleaned DataFrame
rprice_2.head()

In [ ]:
rprice_2.to_csv("rprice_2.csv", index=True)

In [ ]:
key_split = pd.DataFrame(rprice_2['key'].to_list(), index=rprice_2.index)
key_split.columns = ['province', 'commodity', 'year', 'month']

In [ ]:
# 2 -> well-milled rice price
# 3 -> regular milled rice price
key_split["commodity"] = where(key_split["commodity"] == '2', 'milled', 'regular')

In [ ]:
convert_yr = {str(x): str(x + 2010) for x in range(0, (curr_year + 1 - 2010))}
key_split['year'] = key_split['year'].map(convert_yr)

In [ ]:
# months are zero based [0 -> January ... 11 -> December]
convert_mnt = {'0': '01', '1': '02', '2': '03', '3': '04', '4': '05', '5': '06',
                '6': '07', '7': '08', '8': '09', '9': '10', '10': '11', '11': '12'}

key_split['month'] = key_split['month'].map(convert_mnt)

In [ ]:
key_split["province"] = key_split["year"].str.cat(key_split["month"], sep='-')
key_split = key_split.rename(columns={'province': 'date'})
key_split = key_split.drop(columns=['year', 'month'])

In [ ]:
price = pd.DataFrame(rprice_2['values'].to_list(), index=rprice_2.index)
price.columns = ['price']

In [ ]:
key_split = key_split.merge(price, on=key_split.index, how='left')
key_split = key_split.drop(columns=['key_0'])

In [ ]:
key_split

In [ ]:
key_split.drop(key_split[key_split['price'] == '..'].index, inplace=True)

In [ ]:
key_split

#### Prototype - Retail prices stage 3 (combine/concat)

### Functions prototypes

In [2]:
li1 = [['2010', '10'], ['2011', '11'], ['2012', '12'], ['2013', '13']]
li2 = [['2012', '22'], ['2013', '23'], ['2014', '24']]

In [3]:
li1 = pd.DataFrame(li1, columns=['year', 'month'])
li2 = pd.DataFrame(li2, columns=['year', 'month'])

In [ ]:
new = pd.concat([li1, li2])

In [ ]:
mrg = pd.merge(li1, li2, on='year', how='outer')

In [ ]:
mrg

   year month_x month_y
0  2010      10     NaN
1  2011      11     NaN
2  2012      12      22
3  2013      13      23
4  2014     NaN      24

In [ ]:
mrg['month_z'] = mrg['month_y'].fillna(mrg['month_x'])

In [ ]:
mrg

   year month_x month_y month_z
0  2010      10     NaN      10
1  2011      11     NaN      11
2  2012      12      22      22
3  2013      13      23      23
4  2014     NaN      24      24

In [ ]:
mrg = mrg.drop(columns=['month_x', 'month_y'])

In [ ]:
mrg

   year month_z
0  2010      10
1  2011      11
2  2012      22
3  2013      23
4  2014      24

In [9]:
def dataset_concat(df1, df2, on_col, name_col):
  temp = pd.merge(df1, df2, on=on_col, how='outer')
  temp[name_col] = temp[name_col + '_y'].fillna(temp[name_col + '_x'])
  temp = temp.drop(columns=[name_col + '_y', name_col + '_x'])
  return temp

In [10]:
maw = dataset_concat(li1, li2, 'year', 'month')

In [11]:
maw

   year month
0  2010    10
1  2011    11
2  2012    22
3  2013    23
4  2014    24