<a href="https://colab.research.google.com/github/emmanresu/Thesis-Keras/blob/feature%2Fprototype/prototype/requests_prototype.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import json
import requests
import pandas as pd
from datetime import date

query total, commercial, household, nfa stock

In [6]:
# rice stock inventory (monthly total stocks inventory by sector)
url = 'https://openstat.psa.gov.ph/PXWeb/api/v1/en/DB/2E/CS/0032E4ECNV0.px'

curr_year = date.today().year
years = [str(i) for i in range(2000, curr_year + 1)]

# 2. Define your query payload
payload = {
    "query": [
        {
            "code": "Sector",
            "selection": {"filter": "item", "values": ["0", "1", "2", "3"]},
        },  # Rice total, commercial, household, and nfa stocks
        {
            "code": "Year",
            "selection": {"filter": "item", "values": years},
        },  # Years
        {
            "code": "Month",
            "selection": {
                "filter": "item",
                "values": ["0", "1", "2", "3", "4", "5", "6", "7",
                           "8", "9", "10", "11"],
            },
        },  # Jan - Dec
    ],
    "response": {"format": "json"},
}

headers = {"Content-Type": "application/json"}

print("[Sending request to API]")

try:
    # 3. Make the POST request
    response = requests.post(url, data=json.dumps(payload), headers=headers)

    if response.status_code == 200:
        response.encoding = "utf-8-sig"

        data = response.json()

        # 4. Save the data to a local JSON file
        output_filename = "stocks_inventory_data.json"

        with open(output_filename, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=4, ensure_ascii=False)

        print(f"[Successfully retrieved data. Saved locally as: '{output_filename}']")

    else:
        print(f"API Error {response.status_code}: {response.text}")

    df = pd.json_normalize(response.json())
    print_this = df.to_string()
    print_this = print_this.replace("\\n", "\n")
    print(print_this)
except requests.exceptions.RequestException as e:
    print(f"An error occurred while connecting to the API: {e}")

[Sending request to API]
[Successfully retrieved data. Saved locally as: 'stocks_inventory_data.json']
                                                                                                                                                                                                                                                                                                    columns comments                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               data
0  [{'code': 'Sector', 'text': 'Sector', 'type': 'd'}, {'code': 'Year', 'text': 'Year', 'type': 't'}, {'code': 'Month', 'text': 'Month', 'type': 'd'}, {'code': 'Rice and Corn: Monthly Total Stocks Inventory by Sector', 'text': 'Rice and Corn: Monthly Total Stocks Inventory by Sector', 'type': 'c'}]       []  [{'key': ['0', '2000', '0'], 'values': ['2364500.00']}, {'key': ['0', '2000', '1'], 'values': ['2042300.00']}, {'key': ['0', '2000', '2'], 'values': ['1765700.00']}, {'key': ['0', '2000', '3'], 'values': ['1874900.00']}, {'key': ['0', '2000', '4'], 'values': ['2067000.00']}, {'key': ['0', '2000', '5'], 'values': ['1835900.00']}, {'key': ['0', '2000', '6'], 'values': ['1628600.00']}, {'key': ['0', '2000', '7'], 'values': ['1373800.00']}, {'key': ['0', '2000', '8'], 'values': ['1195000.00']}, {'key': ['0', '2000', '9'], 'values': ['1485100.00']}, {'key': ['0', '2000', '10'], 'values': ['2010800.00']}, {'key': ['0', '2000', '11'], 'values': ['2277600.00']}, {'key': ['0', '2001', '0'], 'values': ['2166100.00']}, {'key': ['0', '2001', '1'], 'values': ['1879400.00']}, {'key': ['0', '2001', '2'], 'values': ['1837800.00']}, {'key': ['0', '2001', '3'], 'values': ['2110700.00']}, {'key': ['0', '2001', '4'], 'values': ['2263300.00']}, {'key': ['0', '2001', '5'], 'values': ['2248000.00']}, {'key': ['0', '2001', '6'], 'values': ['2034900.00']}, {'key': ['0', '2001', '7'], 'values': ['1851300.00']}, {'key': ['0', '2001', '8'], 'values': ['1719300.00']}, {'key': ['0', '2001', '9'], 'values': ['1872600.00']}, {'key': ['0', '2001', '10'], 'values': ['2594400.00']}, {'key': ['0', '2001', '11'], 'values': ['2598000.00']}, {'key': ['0', '2002', '0'], 'values': ['2270700.00']}, {'key': ['0', '2002', '1'], 'values': ['1975200.00']}, {'key': ['0', '2002', '2'], 'values': ['1808200.00']}, {'key': ['0', '2002', '3'], 'values': ['1997200.00']}, {'key': ['0', '2002', '4'], 'values': ['2113200.00']}, {'key': ['0', '2002', '5'], 'values': ['1788900.00']}, {'key': ['0', '2002', '6'], 'values': ['1534700.00']}, {'key': ['0', '2002', '7'], 'values': ['1313400.00']}, {'key': ['0', '2002', '8'], 'values': ['1193100.00']}, {'key': ['0', '2002', '9'], 'values': ['1508200.00']}, {'key': ['0', '2002', '10'], 'values': ['2575000.00']}, {'key': ['0', '2002', '11'], 'values': ['2676000.00']}, {'key': ['0', '2003', '0'], 'values': ['2448100.00']}, {'key': ['0', '2003', '1'], 'values': ['2289500.00']}, {'key': ['0', '2003', '2'], 'values': ['2068500.00']}, {'key': ['0', '2003', '3'], 'values': ['2210300.00']}, {'key': ['0', '2003', '4'], 'values': ['2390800.00']}, {'key': ['0', '2003', '5'], 'values': ['2097600.00']}, {'key': ['0', '2003', '6'], 'values': ['1806100.00']}, {'key': ['0', '2003', '7'], 'values': ['1566500.00']}, {'key': ['0', '2003', '8'], 'values': ['1399600.00']}, {'key': ['0', '2003', '9'], 'values': ['1742400.00']}, {'key': ['0', '2003', '10'], 'values': ['2525000.00']}, {'key': ['0', '2003', '11'], 'values': ['2607000.00']}, {'key': ['0', '2004', '0'], 'values': ['2362100.00']}, {'key': ['0', '2004', '1'], 'values': ['2068000.00']}, {'key': ['0', '2004', '2'], 'values': ['1857700.00']}, {'key': ['0', '2004', '3'], 'values': ['2147400.00']}, {'key': ['0', '2004', '4'], 'values': ['2338700.00']}, {'key': ['0', '2004', '5'], 'values': ['1880100.00']}, {'key': ['0', '2004', '6'], 'values': ['1577400.00']}, {'key': ['0', '2004', '7'], 'values': ['1340800.00']}, {'key': ['0', '2004', '8'], 'values': ['1189100.00']}, {'key': ['0', '2004', '9'], 'values': ['1559500.00']}, {'key': ['0', '2004', '10'], 'values': ['2289800.00']}, {'key': ['0', '2004', '11'], 'values': ['2404500.00']}, {'key': ['0', '2005', '0'], 'values': ['2050900.00']}, {'key': ['0', '2005', '1'], 'values': ['1777400.00']}, {'key': ['0', '2005', '2'], 'values': ['1455600.00']}, {'key': ['0', '2005', '3'], 'values': ['1744700.00']}, {'key': ['0', '2005', '4'], 'values': ['1999200.00']}, {'key': ['0', '2005', '5'], 'values': ['1879300.00']}, {'key': ['0', '2005', '6'], 'values': ['1638200.00']}, {'key': ['0', '2005', '7'], 'values': ['1457100.00']}, {'key': ['0', '2005', '8'], 'values': ['1308000.00']}, {'key': ['0', '2005', '9'], 'values': ['1592700.00']}, {'key': ['0', '2005', '10'], 'values': ['2255300.00']}, {'key': ['0', '2005', '11'], 'values': ['2406200.00']}, {'key': ['0', '2006', '0'], 'values': ['2094300.00']}, {'key': ['0', '2006', '1'], 'values': ['1885900.00']}, {'key': ['0', '2006', '2'], 'values': ['1719900.00']}, {'key': ['0', '2006', '3'], 'values': ['2192900.00']}, {'key': ['0', '2006', '4'], 'values': ['2422500.00']}, {'key': ['0', '2006', '5'], 'values': ['2217300.00']}, {'key': ['0', '2006', '6'], 'values': ['1960100.00']}, {'key': ['0', '2006', '7'], 'values': ['1754200.00']}, {'key': ['0', '2006', '8'], 'values': ['1649500.00']}, {'key': ['0', '2006', '9'], 'values': ['1825300.00']}, {'key': ['0', '2006', '10'], 'values': ['2435200.00']}, {'key': ['0', '2006', '11'], 'values': ['2580400.00']}, {'key': ['0', '2007', '0'], 'values': ['2253100.00']}, {'key': ['0', '2007', '1'], 'values': ['1841300.00']}, {'key': ['0', '2007', '2'], 'values': ['1588600.00']}, {'key': ['0', '2007', '3'], 'values': ['1654500.00']}, {'key': ['0', '2007', '4'], 'values': ['1893500.00']}, {'key': ['0', '2007', '5'], 'values': ['1629100.00']}, {'key': ['0', '2007', '6'], 'values': ['1529100.00']}, {'key': ['0', '2007', '7'], 'values': ['1354600.00']}, {'key': ['0', '2007', '8'], 'values': ['1135800.00']}, {'key': ['0', '2007', '9'], 'values': ['1375100.00']}, {'key': ['0', '2007', '10'], 'values': ['2038300.00']}, {'key': ['0', '2007', '11'], 'values': ['2291500.00']}, {'key': ['0', '2008', '0'], 'values': ['2172300.00']}, {'key': ['0', '2008', '1'], 'values': ['1834900.00']}, {'key': ['0', '2008', '2'], 'values': ['1688700.00']}, {'key': ['0', '2008', '3'], 'values': ['1891400.00']}, ...]

query wholesale rice price 2000 - 2010

notes: needs editing

In [ ]:
# rice whole sale price 2000-2010
url = 'https://openstat.psa.gov.ph/PXWeb/api/v1/en/DB/2M/WS/0012M4AWP01.px'

# curr_year = date.today().year
# years = [str(i) for i in range(2000, curr_year + 1)]

# 2. Define your query payload
payload = {
    "query": [
        {
            "code": "Region Province",
            "selection": {"filter": "item", "values": ["00"]},
        },  # Rice total, commercial, household, and nfa stocks
        {
            "code": "Commodity",
            "selection": {"filter": "item", "values": ["2", "3"]},
        },
        {
            "code": "Year",
            "selection": {"filter": "item", "values": ["10", "11"]},
        },  # Years [10 = 2010 | 11 = 2011 | 12 = 2012 ... ]
        {
            "code": "Month",
            "selection": {
                "filter": "item",
                "values": ["0", "1", "2", "3", "4", "5", "6", "7",
                           "8", "9", "10", "11"],
            },
        },  # Jan - Dec
    ],
    "response": {"format": "json"},
}

headers = {"Content-Type": "application/json"}

print("[Sending request to API]")

try:
    # 3. Make the POST request
    response = requests.post(url, data=json.dumps(payload), headers=headers)

    if response.status_code == 200:
        response.encoding = "utf-8-sig"

        data = response.json()

        # 4. Save the data to a local JSON file
        output_filename = "stocks_inventory_data.json"

        with open(output_filename, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=4, ensure_ascii=False)

        print(f"[Successfully retrieved data. Saved locally as: '{output_filename}']")

    else:
        print(f"API Error {response.status_code}: {response.text}")

    df = pd.json_normalize(response.json())
    print_this = df.to_string()
    print_this = print_this.replace("\\n", "\n")
    print(print_this)
except requests.exceptions.RequestException as e:
    print(f"An error occurred while connecting to the API: {e}")

[Sending request to API]
[Successfully retrieved data. Saved locally as: 'stocks_inventory_data.json']
                                                                                                                                                                                                                                                                                                                                                                                           columns                                                                                                   comments                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      data
0  [{'code': 'Region Province', 'text': 'Region Province', 'type': 'd'}, {'code': 'Commodity', 'text': 'Commodity', 'type': 'd'}, {'code': 'Year', 'text': 'Year', 'type': 't'}, {'code': 'Month', 'text': 'Month', 'type': 'd'}, {'code': 'Cereals: Wholesale Selling Prices of Agricultural Commodities', 'text': 'Cereals: Wholesale Selling Prices of Agricultural Commodities', 'type': 'c'}]  [{'variable': 'Month', 'value': '11', 'comment': 'w/o MM and Eastern Samar
(No report yet) 02-06-15
'}]  [{'key': ['00', '1', '10', '0'], 'values': ['19.52']}, {'key': ['00', '1', '10', '1'], 'values': ['19.63']}, {'key': ['00', '1', '10', '2'], 'values': ['19.74']}, {'key': ['00', '1', '10', '3'], 'values': ['19.77']}, {'key': ['00', '1', '10', '4'], 'values': ['19.92']}, {'key': ['00', '1', '10', '5'], 'values': ['20.08']}, {'key': ['00', '1', '10', '6'], 'values': ['20.18']}, {'key': ['00', '1', '10', '7'], 'values': ['20.28']}, {'key': ['00', '1', '10', '8'], 'values': ['20.39']}, {'key': ['00', '1', '10', '9'], 'values': ['19.92']}, {'key': ['00', '1', '10', '10'], 'values': ['19.97']}, {'key': ['00', '1', '10', '11'], 'values': ['19.80']}, {'key': ['00', '1', '11', '0'], 'values': ['19.87']}, {'key': ['00', '1', '11', '1'], 'values': ['19.86']}, {'key': ['00', '1', '11', '2'], 'values': ['19.71']}, {'key': ['00', '1', '11', '3'], 'values': ['19.74']}, {'key': ['00', '1', '11', '4'], 'values': ['19.81']}, {'key': ['00', '1', '11', '5'], 'values': ['19.98']}, {'key': ['00', '1', '11', '6'], 'values': ['20.24']}, {'key': ['00', '1', '11', '7'], 'values': ['20.21']}, {'key': ['00', '1', '11', '8'], 'values': ['20.33']}, {'key': ['00', '1', '11', '9'], 'values': ['20.17']}, {'key': ['00', '1', '11', '10'], 'values': ['20.21']}, {'key': ['00', '1', '11', '11'], 'values': ['20.03']}, {'key': ['00', '2', '10', '0'], 'values': ['17.38']}, {'key': ['00', '2', '10', '1'], 'values': ['17.57']}, {'key': ['00', '2', '10', '2'], 'values': ['17.64']}, {'key': ['00', '2', '10', '3'], 'values': ['17.62']}, {'key': ['00', '2', '10', '4'], 'values': ['17.75']}, {'key': ['00', '2', '10', '5'], 'values': ['17.86']}, {'key': ['00', '2', '10', '6'], 'values': ['18.13']}, {'key': ['00', '2', '10', '7'], 'values': ['18.31']}, {'key': ['00', '2', '10', '8'], 'values': ['18.16']}, {'key': ['00', '2', '10', '9'], 'values': ['17.74']}, {'key': ['00', '2', '10', '10'], 'values': ['17.56']}, {'key': ['00', '2', '10', '11'], 'values': ['17.51']}, {'key': ['00', '2', '11', '0'], 'values': ['17.59']}, {'key': ['00', '2', '11', '1'], 'values': ['17.54']}, {'key': ['00', '2', '11', '2'], 'values': ['17.55']}, {'key': ['00', '2', '11', '3'], 'values': ['17.51']}, {'key': ['00', '2', '11', '4'], 'values': ['17.48']}, {'key': ['00', '2', '11', '5'], 'values': ['17.65']}, {'key': ['00', '2', '11', '6'], 'values': ['17.89']}, {'key': ['00', '2', '11', '7'], 'values': ['18.00']}, {'key': ['00', '2', '11', '8'], 'values': ['17.78']}, {'key': ['00', '2', '11', '9'], 'values': ['17.46']}, {'key': ['00', '2', '11', '10'], 'values': ['17.37']}, {'key': ['00', '2', '11', '11'], 'values': ['17.44']}]

query wholesale price 2010 - current year

notes: improve how to access year

In [ ]:
# rice whole sale price 2000-2010
url = 'https://openstat.psa.gov.ph/PXWeb/api/v1/en/DB/2M/NWSNEW/0052M4AWB01.px'

# curr_year = date.today().year
# years = [str(i) for i in range(2000, curr_year + 1)]
year = [str(i) for i in range(20)]

# 2. Define your query payload
payload = {
    "query": [
        {
            "code": "Geolocation",
            "selection": {"filter": "item", "values": ["0"]},
        },  # Rice total, commercial, household, and nfa stocks
        {
            "code": "Commodity",
            "selection": {"filter": "item", "values": ["2", "3"]},
        },
        {
            "code": "year",
            "selection": {"filter": "item", "values": year},
        },  # Years [10 = 2010 | 11 = 2011 | 12 = 2012 ... ]
        {
            "code": "period",
            "selection": {
                "filter": "item",
                "values": ["0", "1", "2", "3", "4", "5", "6", "7",
                           "8", "9", "10", "11"],
            },
        },  # Jan - Dec
    ],
    "response": {"format": "json"},
}

headers = {"Content-Type": "application/json"}

print("[Sending request to API]")

try:
    # 3. Make the POST request
    response = requests.post(url, data=json.dumps(payload), headers=headers)

    if response.status_code == 200:
        response.encoding = "utf-8-sig"

        data = response.json()

        # 4. Save the data to a local JSON file
        output_filename = "stocks_inventory_data.json"

        with open(output_filename, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=4, ensure_ascii=False)

        print(f"[Successfully retrieved data. Saved locally as: '{output_filename}']")

    else:
        print(f"API Error {response.status_code}: {response.text}")

    df = pd.json_normalize(response.json())
    print_this = df.to_string()
    print_this = print_this.replace("\\n", "\n")
    print(print_this)
except requests.exceptions.RequestException as e:
    print(f"An error occurred while connecting to the API: {e}")

[Sending request to API]
[Successfully retrieved data. Saved locally as: 'stocks_inventory_data.json']
                                                                                                                                                                                                                                                                                                                                                                                                                                                           columns comments                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   data
0  [{'code': 'Geolocation', 'text': 'Geolocation', 'type': 'd'}, {'code': 'Commodity', 'text': 'Commodity', 'type': 'd'}, {'code': 'year', 'text': 'year', 'type': 't'}, {'code': 'period', 'text': 'period', 'type': 'd'}, {'code': 'Wholesale Prices of Selected Agricultural Commodities by Commodity, Geolocation, year and period', 'text': 'Wholesale Prices of Selected Agricultural Commodities by Commodity, Geolocation, year and period', 'type': 'c'}]       []  [{'key': ['0', '2', '0', '0'], 'values': ['31.27']}, {'key': ['0', '2', '0', '1'], 'values': ['31.73']}, {'key': ['0', '2', '0', '2'], 'values': ['31.99']}, {'key': ['0', '2', '0', '3'], 'values': ['31.58']}, {'key': ['0', '2', '0', '4'], 'values': ['31.38']}, {'key': ['0', '2', '0', '5'], 'values': ['31.60']}, {'key': ['0', '2', '0', '6'], 'values': ['31.72']}, {'key': ['0', '2', '0', '7'], 'values': ['31.69']}, {'key': ['0', '2', '0', '8'], 'values': ['31.55']}, {'key': ['0', '2', '0', '9'], 'values': ['31.12']}, {'key': ['0', '2', '0', '10'], 'values': ['30.92']}, {'key': ['0', '2', '0', '11'], 'values': ['31.17']}, {'key': ['0', '2', '1', '0'], 'values': ['31.54']}, {'key': ['0', '2', '1', '1'], 'values': ['31.90']}, {'key': ['0', '2', '1', '2'], 'values': ['31.90']}, {'key': ['0', '2', '1', '3'], 'values': ['32.02']}, {'key': ['0', '2', '1', '4'], 'values': ['32.11']}, {'key': ['0', '2', '1', '5'], 'values': ['32.17']}, {'key': ['0', '2', '1', '6'], 'values': ['32.19']}, {'key': ['0', '2', '1', '7'], 'values': ['32.22']}, {'key': ['0', '2', '1', '8'], 'values': ['32.15']}, {'key': ['0', '2', '1', '9'], 'values': ['32.09']}, {'key': ['0', '2', '1', '10'], 'values': ['32.15']}, {'key': ['0', '2', '1', '11'], 'values': ['32.28']}, {'key': ['0', '2', '2', '0'], 'values': ['32.54']}, {'key': ['0', '2', '2', '1'], 'values': ['32.38']}, {'key': ['0', '2', '2', '2'], 'values': ['32.59']}, {'key': ['0', '2', '2', '3'], 'values': ['32.70']}, {'key': ['0', '2', '2', '4'], 'values': ['32.78']}, {'key': ['0', '2', '2', '5'], 'values': ['32.90']}, {'key': ['0', '2', '2', '6'], 'values': ['33.19']}, {'key': ['0', '2', '2', '7'], 'values': ['33.26']}, {'key': ['0', '2', '2', '8'], 'values': ['33.04']}, {'key': ['0', '2', '2', '9'], 'values': ['32.75']}, {'key': ['0', '2', '2', '10'], 'values': ['32.75']}, {'key': ['0', '2', '2', '11'], 'values': ['32.73']}, {'key': ['0', '2', '3', '0'], 'values': ['32.77']}, {'key': ['0', '2', '3', '1'], 'values': ['32.78']}, {'key': ['0', '2', '3', '2'], 'values': ['32.79']}, {'key': ['0', '2', '3', '3'], 'values': ['32.72']}, {'key': ['0', '2', '3', '4'], 'values': ['32.80']}, {'key': ['0', '2', '3', '5'], 'values': ['33.18']}, {'key': ['0', '2', '3', '6'], 'values': ['34.51']}, {'key': ['0', '2', '3', '7'], 'values': ['36.01']}, {'key': ['0', '2', '3', '8'], 'values': ['37.02']}, {'key': ['0', '2', '3', '9'], 'values': ['36.22']}, {'key': ['0', '2', '3', '10'], 'values': ['36.37']}, {'key': ['0', '2', '3', '11'], 'values': ['36.78']}, {'key': ['0', '2', '4', '0'], 'values': ['37.12']}, {'key': ['0', '2', '4', '1'], 'values': ['37.69']}, {'key': ['0', '2', '4', '2'], 'values': ['38.56']}, {'key': ['0', '2', '4', '3'], 'values': ['38.94']}, {'key': ['0', '2', '4', '4'], 'values': ['39.44']}, {'key': ['0', '2', '4', '5'], 'values': ['40.07']}, {'key': ['0', '2', '4', '6'], 'values': ['41.01']}, {'key': ['0', '2', '4', '7'], 'values': ['41.38']}, {'key': ['0', '2', '4', '8'], 'values': ['41.12']}, {'key': ['0', '2', '4', '9'], 'values': ['40.62']}, {'key': ['0', '2', '4', '10'], 'values': ['40.05']}, {'key': ['0', '2', '4', '11'], 'values': ['39.96']}, {'key': ['0', '2', '5', '0'], 'values': ['39.13']}, {'key': ['0', '2', '5', '1'], 'values': ['38.66']}, {'key': ['0', '2', '5', '2'], 'values': ['38.23']}, {'key': ['0', '2', '5', '3'], 'values': ['38.24']}, {'key': ['0', '2', '5', '4'], 'values': ['38.73']}, {'key': ['0', '2', '5', '5'], 'values': ['38.12']}, {'key': ['0', '2', '5', '6'], 'values': ['38.17']}, {'key': ['0', '2', '5', '7'], 'values': ['38.34']}, {'key': ['0', '2', '5', '8'], 'values': ['38.10']}, {'key': ['0', '2', '5', '9'], 'values': ['38.05']}, {'key': ['0', '2', '5', '10'], 'values': ['37.27']}, {'key': ['0', '2', '5', '11'], 'values': ['37.55']}, {'key': ['0', '2', '6', '0'], 'values': ['37.35']}, {'key': ['0', '2', '6', '1'], 'values': ['37.62']}, {'key': ['0', '2', '6', '2'], 'values': ['37.82']}, {'key': ['0', '2', '6', '3'], 'values': ['37.81']}, {'key': ['0', '2', '6', '4'], 'values': ['37.87']}, {'key': ['0', '2', '6', '5'], 'values': ['38.32']}, {'key': ['0', '2', '6', '6'], 'values': ['38.57']}, {'key': ['0', '2', '6', '7'], 'values': ['38.42']}, {'key': ['0', '2', '6', '8'], 'values': ['38.66']}, {'key': ['0', '2', '6', '9'], 'values': ['37.93']}, {'key': ['0', '2', '6', '10'], 'values': ['37.64']}, {'key': ['0', '2', '6', '11'], 'values': ['37.86']}, {'key': ['0', '2', '7', '0'], 'values': ['38.27']}, {'key': ['0', '2', '7', '1'], 'values': ['38.54']}, {'key': ['0', '2', '7', '2'], 'values': ['38.47']}, {'key': ['0', '2', '7', '3'], 'values': ['38.65']}, {'key': ['0', '2', '7', '4'], 'values': ['38.71']}, {'key': ['0', '2', '7', '5'], 'values': ['38.84']}, {'key': ['0', '2', '7', '6'], 'values': ['39.04']}, {'key': ['0', '2', '7', '7'], 'values': ['39.28']}, {'key': ['0', '2', '7', '8'], 'values': ['39.23']}, {'key': ['0', '2', '7', '9'], 'values': ['39.14']}, {'key': ['0', '2', '7', '10'], 'values': ['39.41']}, {'key': ['0', '2', '7', '11'], 'values': ['39.25']}, {'key': ['0', '2', '8', '0'], 'values': ['39.74']}, {'key': ['0', '2', '8', '1'], 'values': ['40.58']}, {'key': ['0', '2', '8', '2'], 'values': ['40.96']}, {'key': ['0', '2', '8', '3'], 'values': ['41.16']}, ...]

query retail price 2000 - 2010

In [15]:
# rice whole sale price 2000-2010
url = 'https://openstat.psa.gov.ph/PXWeb/api/v1/en/DB/2M/RP/0042M4ARP01.px'

# curr_year = date.today().year
# years = [str(i) for i in range(2000, curr_year + 1)]
year = [str(i) for i in range(20)]

# 2. Define your query payload
payload = {
    "query": [
        {
            "code": "Geolocation",
            "selection": {"filter": "item", "values": ["00"]},
        },  # Philippines
        {
            "code": "Commodity",
            "selection": {"filter": "item", "values": ["2", "3"]},
        },  # well milled and regular price
        {
            "code": "Year",
            "selection": {"filter": "item", "values": [10, 11, 12, 13, 14, 15, 16,
                                                       17, 18, 19, 20]},
        },  # Years [10 = 2010 | 11 = 2011 | 12 = 2012 ... ]
        {
            "code": "Period",
            "selection": {
                "filter": "item",
                "values": ["0", "1", "2", "3", "4", "5", "6", "7",
                           "8", "9", "10", "11"],
            },
        },  # Jan - Dec
    ],
    "response": {"format": "json"},
}

headers = {"Content-Type": "application/json"}

print("[Sending request to API]")

try:
    # 3. Make the POST request
    response = requests.post(url, data=json.dumps(payload), headers=headers)

    if response.status_code == 200:
        response.encoding = "utf-8-sig"

        data = response.json()

        # 4. Save the data to a local JSON file
        output_filename = "stocks_inventory_data.json"

        with open(output_filename, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=4, ensure_ascii=False)

        print(f"[Successfully retrieved data. Saved locally as: '{output_filename}']")

    else:
        print(f"API Error {response.status_code}: {response.text}")

    df = pd.json_normalize(response.json())
    print_this = df.to_string()
    print_this = print_this.replace("\\n", "\n")
    print(print_this)
except requests.exceptions.RequestException as e:
    print(f"An error occurred while connecting to the API: {e}")

[Sending request to API]
[Successfully retrieved data. Saved locally as: 'stocks_inventory_data.json']
                                                                                                                                                                                                                                                                                                                                                                                             columns                                                                                                    comments                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           data
0  [{'code': 'Geolocation', 'text': 'Geolocation', 'type': 'd'}, {'code': 'Commodity', 'text': 'Commodity', 'type': 'd'}, {'code': 'Year', 'text': 'Year', 'type': 't'}, {'code': 'Period', 'text': 'Period', 'type': 'd'}, {'code': 'Cereals: Retail Prices by Geolocation, Commodity, Year and Period', 'text': 'Cereals: Retail Prices by Geolocation, Commodity, Year and Period', 'type': 'c'}]  [{'variable': 'Period', 'value': '11', 'comment': 'w/o MM and Eastern Samar
(No report yet) 02-06-15
'}]  [{'key': ['00', '2', '10', '0'], 'values': ['19.00']}, {'key': ['00', '2', '10', '1'], 'values': ['19.12']}, {'key': ['00', '2', '10', '2'], 'values': ['19.22']}, {'key': ['00', '2', '10', '3'], 'values': ['19.21']}, {'key': ['00', '2', '10', '4'], 'values': ['19.27']}, {'key': ['00', '2', '10', '5'], 'values': ['19.38']}, {'key': ['00', '2', '10', '6'], 'values': ['19.74']}, {'key': ['00', '2', '10', '7'], 'values': ['19.99']}, {'key': ['00', '2', '10', '8'], 'values': ['19.96']}, {'key': ['00', '2', '10', '9'], 'values': ['19.64']}, {'key': ['00', '2', '10', '10'], 'values': ['19.48']}, {'key': ['00', '2', '10', '11'], 'values': ['19.37']}, {'key': ['00', '2', '11', '0'], 'values': ['19.37']}, {'key': ['00', '2', '11', '1'], 'values': ['19.36']}, {'key': ['00', '2', '11', '2'], 'values': ['19.36']}, {'key': ['00', '2', '11', '3'], 'values': ['19.29']}, {'key': ['00', '2', '11', '4'], 'values': ['19.33']}, {'key': ['00', '2', '11', '5'], 'values': ['19.45']}, {'key': ['00', '2', '11', '6'], 'values': ['19.64']}, {'key': ['00', '2', '11', '7'], 'values': ['19.68']}, {'key': ['00', '2', '11', '8'], 'values': ['19.57']}, {'key': ['00', '2', '11', '9'], 'values': ['19.47']}, {'key': ['00', '2', '11', '10'], 'values': ['19.30']}, {'key': ['00', '2', '11', '11'], 'values': ['19.31']}, {'key': ['00', '2', '12', '0'], 'values': ['19.33']}, {'key': ['00', '2', '12', '1'], 'values': ['19.40']}, {'key': ['00', '2', '12', '2'], 'values': ['19.41']}, {'key': ['00', '2', '12', '3'], 'values': ['19.42']}, {'key': ['00', '2', '12', '4'], 'values': ['19.49']}, {'key': ['00', '2', '12', '5'], 'values': ['19.69']}, {'key': ['00', '2', '12', '6'], 'values': ['20.16']}, {'key': ['00', '2', '12', '7'], 'values': ['21.00']}, {'key': ['00', '2', '12', '8'], 'values': ['21.31']}, {'key': ['00', '2', '12', '9'], 'values': ['20.55']}, {'key': ['00', '2', '12', '10'], 'values': ['20.02']}, {'key': ['00', '2', '12', '11'], 'values': ['19.94']}, {'key': ['00', '2', '13', '0'], 'values': ['19.92']}, {'key': ['00', '2', '13', '1'], 'values': ['19.85']}, {'key': ['00', '2', '13', '2'], 'values': ['19.86']}, {'key': ['00', '2', '13', '3'], 'values': ['19.92']}, {'key': ['00', '2', '13', '4'], 'values': ['20.13']}, {'key': ['00', '2', '13', '5'], 'values': ['20.44']}, {'key': ['00', '2', '13', '6'], 'values': ['20.70']}, {'key': ['00', '2', '13', '7'], 'values': ['20.89']}, {'key': ['00', '2', '13', '8'], 'values': ['20.57']}, {'key': ['00', '2', '13', '9'], 'values': ['20.20']}, {'key': ['00', '2', '13', '10'], 'values': ['19.95']}, {'key': ['00', '2', '13', '11'], 'values': ['19.97']}, {'key': ['00', '2', '14', '0'], 'values': ['20.05']}, {'key': ['00', '2', '14', '1'], 'values': ['20.06']}, {'key': ['00', '2', '14', '2'], 'values': ['20.46']}, {'key': ['00', '2', '14', '3'], 'values': ['20.71']}, {'key': ['00', '2', '14', '4'], 'values': ['20.90']}, {'key': ['00', '2', '14', '5'], 'values': ['21.17']}, {'key': ['00', '2', '14', '6'], 'values': ['21.75']}, {'key': ['00', '2', '14', '7'], 'values': ['22.02']}, {'key': ['00', '2', '14', '8'], 'values': ['21.82']}, {'key': ['00', '2', '14', '9'], 'values': ['21.24']}, {'key': ['00', '2', '14', '10'], 'values': ['21.07']}, {'key': ['00', '2', '14', '11'], 'values': ['21.23']}, {'key': ['00', '2', '15', '0'], 'values': ['21.51']}, {'key': ['00', '2', '15', '1'], 'values': ['21.56']}, {'key': ['00', '2', '15', '2'], 'values': ['21.83']}, {'key': ['00', '2', '15', '3'], 'values': ['22.62']}, {'key': ['00', '2', '15', '4'], 'values': ['23.12']}, {'key': ['00', '2', '15', '5'], 'values': ['23.27']}, {'key': ['00', '2', '15', '6'], 'values': ['23.60']}, {'key': ['00', '2', '15', '7'], 'values': ['23.91']}, {'key': ['00', '2', '15', '8'], 'values': ['23.62']}, {'key': ['00', '2', '15', '9'], 'values': ['23.27']}, {'key': ['00', '2', '15', '10'], 'values': ['23.12']}, {'key': ['00', '2', '15', '11'], 'values': ['23.15']}, {'key': ['00', '2', '16', '0'], 'values': ['23.23']}, {'key': ['00', '2', '16', '1'], 'values': ['23.36']}, {'key': ['00', '2', '16', '2'], 'values': ['23.48']}, {'key': ['00', '2', '16', '3'], 'values': ['23.50']}, {'key': ['00', '2', '16', '4'], 'values': ['23.59']}, {'key': ['00', '2', '16', '5'], 'values': ['23.69']}, {'key': ['00', '2', '16', '6'], 'values': ['23.78']}, {'key': ['00', '2', '16', '7'], 'values': ['23.85']}, {'key': ['00', '2', '16', '8'], 'values': ['23.71']}, {'key': ['00', '2', '16', '9'], 'values': ['23.50']}, {'key': ['00', '2', '16', '10'], 'values': ['23.46']}, {'key': ['00', '2', '16', '11'], 'values': ['23.54']}, {'key': ['00', '2', '17', '0'], 'values': ['23.72']}, {'key': ['00', '2', '17', '1'], 'values': ['23.81']}, {'key': ['00', '2', '17', '2'], 'values': ['24.07']}, {'key': ['00', '2', '17', '3'], 'values': ['24.17']}, {'key': ['00', '2', '17', '4'], 'values': ['24.29']}, {'key': ['00', '2', '17', '5'], 'values': ['24.38']}, {'key': ['00', '2', '17', '6'], 'values': ['24.69']}, {'key': ['00', '2', '17', '7'], 'values': ['25.09']}, {'key': ['00', '2', '17', '8'], 'values': ['25.72']}, {'key': ['00', '2', '17', '9'], 'values': ['25.70']}, {'key': ['00', '2', '17', '10'], 'values': ['25.49']}, {'key': ['00', '2', '17', '11'], 'values': ['25.53']}, {'key': ['00', '2', '18', '0'], 'values': ['25.84']}, {'key': ['00', '2', '18', '1'], 'values': ['26.08']}, {'key': ['00', '2', '18', '2'], 'values': ['27.57']}, {'key': ['00', '2', '18', '3'], 'values': ['32.20']}, ...]

query retail price 2010 - present

notes: double check url and the web automation data retrieval

In [17]:
# rice whole sale price 2000-2010
url = 'https://openstat.psa.gov.ph/PXWeb/api/v1/en/DB/2M/2018NEW/0042M4ARN01.px'

# curr_year = date.today().year
# years = [str(i) for i in range(2000, curr_year + 1)]
year = [str(i) for i in range(20)]

# 2. Define your query payload
payload = {
    "query": [
        {
            "code": "Geolocation",
            "selection": {"filter": "item", "values": ["000000000"]},
        },  # Philippines
        {
            "code": "Commodity",
            "selection": {"filter": "item", "values": ["0", "1"]},
        },  # well milled and regular price
        {
            "code": "Year",
            "selection": {"filter": "item", "values": [0, 1, 2, 3, 4, 5,
                                                       6, 7, 8, 9, 10]},
        },  # Years [up to present]
        {
            "code": "Period",
            "selection": {
                "filter": "item",
                "values": ["0", "1", "2", "3", "4", "5", "6", "7",
                           "8", "9", "10", "11"],
            },
        },  # Jan - Dec
    ],
    "response": {"format": "json"},
}

headers = {"Content-Type": "application/json"}

print("[Sending request to API]")

try:
    # 3. Make the POST request
    response = requests.post(url, data=json.dumps(payload), headers=headers)

    if response.status_code == 200:
        response.encoding = "utf-8-sig"

        data = response.json()

        # 4. Save the data to a local JSON file
        output_filename = "stocks_inventory_data.json"

        with open(output_filename, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=4, ensure_ascii=False)

        print(f"[Successfully retrieved data. Saved locally as: '{output_filename}']")

    else:
        print(f"API Error {response.status_code}: {response.text}")

    df = pd.json_normalize(response.json())
    print_this = df.to_string()
    print_this = print_this.replace("\\n", "\n")
    print(print_this)
except requests.exceptions.RequestException as e:
    print(f"An error occurred while connecting to the API: {e}")

[Sending request to API]
[Successfully retrieved data. Saved locally as: 'stocks_inventory_data.json']
                                                                                                                                                                                                                                                                                                                                             columns comments                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   data
0  [{'code': 'Geolocation', 'text': 'Geolocation', 'type': 'd'}, {'code': 'Commodity', 'text': 'Commodity', 'type': 'd'}, {'code': 'Year', 'text': 'Year', 'type': 't'}, {'code': 'Period', 'text': 'Period', 'type': 'd'}, {'code': 'Retail Prices of Agricultural Commodities', 'text': 'Retail Prices of Agricultural Commodities', 'type': 'c'}]       []  [{'key': ['000000000', '0', '0', '0'], 'values': ['44.77']}, {'key': ['000000000', '0', '0', '1'], 'values': ['45.25']}, {'key': ['000000000', '0', '0', '2'], 'values': ['45.79']}, {'key': ['000000000', '0', '0', '3'], 'values': ['46.01']}, {'key': ['000000000', '0', '0', '4'], 'values': ['46.32']}, {'key': ['000000000', '0', '0', '5'], 'values': ['46.55']}, {'key': ['000000000', '0', '0', '6'], 'values': ['46.99']}, {'key': ['000000000', '0', '0', '7'], 'values': ['48.11']}, {'key': ['000000000', '0', '0', '8'], 'values': ['49.85']}, {'key': ['000000000', '0', '0', '9'], 'values': ['50.21']}, {'key': ['000000000', '0', '0', '10'], 'values': ['49.03']}, {'key': ['000000000', '0', '0', '11'], 'values': ['47.88']}, {'key': ['000000000', '0', '1', '0'], 'values': ['47.23']}, {'key': ['000000000', '0', '1', '1'], 'values': ['46.99']}, {'key': ['000000000', '0', '1', '2'], 'values': ['46.66']}, {'key': ['000000000', '0', '1', '3'], 'values': ['46.22']}, {'key': ['000000000', '0', '1', '4'], 'values': ['45.74']}, {'key': ['000000000', '0', '1', '5'], 'values': ['45.42']}, {'key': ['000000000', '0', '1', '6'], 'values': ['45.05']}, {'key': ['000000000', '0', '1', '7'], 'values': ['44.79']}, {'key': ['000000000', '0', '1', '8'], 'values': ['44.33']}, {'key': ['000000000', '0', '1', '9'], 'values': ['43.88']}, {'key': ['000000000', '0', '1', '10'], 'values': ['43.44']}, {'key': ['000000000', '0', '1', '11'], 'values': ['43.18']}, {'key': ['000000000', '0', '2', '0'], 'values': ['43.02']}, {'key': ['000000000', '0', '2', '1'], 'values': ['42.86']}, {'key': ['000000000', '0', '2', '2'], 'values': ['42.66']}, {'key': ['000000000', '0', '2', '3'], 'values': ['43.61']}, {'key': ['000000000', '0', '2', '4'], 'values': ['43.88']}, {'key': ['000000000', '0', '2', '5'], 'values': ['44.09']}, {'key': ['000000000', '0', '2', '6'], 'values': ['44.16']}, {'key': ['000000000', '0', '2', '7'], 'values': ['44.05']}, {'key': ['000000000', '0', '2', '8'], 'values': ['43.83']}, {'key': ['000000000', '0', '2', '9'], 'values': ['43.46']}, {'key': ['000000000', '0', '2', '10'], 'values': ['43.29']}, {'key': ['000000000', '0', '2', '11'], 'values': ['43.27']}, {'key': ['000000000', '0', '3', '0'], 'values': ['42.84']}, {'key': ['000000000', '0', '3', '1'], 'values': ['42.98']}, {'key': ['000000000', '0', '3', '2'], 'values': ['43.07']}, {'key': ['000000000', '0', '3', '3'], 'values': ['43.13']}, {'key': ['000000000', '0', '3', '4'], 'values': ['43.18']}, {'key': ['000000000', '0', '3', '5'], 'values': ['43.16']}, {'key': ['000000000', '0', '3', '6'], 'values': ['43.27']}, {'key': ['000000000', '0', '3', '7'], 'values': ['43.45']}, {'key': ['000000000', '0', '3', '8'], 'values': ['43.37']}, {'key': ['000000000', '0', '3', '9'], 'values': ['43.27']}, {'key': ['000000000', '0', '3', '10'], 'values': ['43.25']}, {'key': ['000000000', '0', '3', '11'], 'values': ['43.22']}, {'key': ['000000000', '0', '4', '0'], 'values': ['43.13']}, {'key': ['000000000', '0', '4', '1'], 'values': ['43.17']}, {'key': ['000000000', '0', '4', '2'], 'values': ['43.21']}, {'key': ['000000000', '0', '4', '3'], 'values': ['43.31']}, {'key': ['000000000', '0', '4', '4'], 'values': ['43.42']}, {'key': ['000000000', '0', '4', '5'], 'values': ['43.62']}, {'key': ['000000000', '0', '4', '6'], 'values': ['43.72']}, {'key': ['000000000', '0', '4', '7'], 'values': ['43.88']}, {'key': ['000000000', '0', '4', '8'], 'values': ['43.80']}, {'key': ['000000000', '0', '4', '9'], 'values': ['43.82']}, {'key': ['000000000', '0', '4', '10'], 'values': ['43.86']}, {'key': ['000000000', '0', '4', '11'], 'values': ['43.98']}, {'key': ['000000000', '0', '5', '0'], 'values': ['43.92']}, {'key': ['000000000', '0', '5', '1'], 'values': ['43.99']}, {'key': ['000000000', '0', '5', '2'], 'values': ['44.23']}, {'key': ['000000000', '0', '5', '3'], 'values': ['44.53']}, {'key': ['000000000', '0', '5', '4'], 'values': ['44.78']}, {'key': ['000000000', '0', '5', '5'], 'values': ['44.99']}, {'key': ['000000000', '0', '5', '6'], 'values': ['45.32']}, {'key': ['000000000', '0', '5', '7'], 'values': ['47.65']}, {'key': ['000000000', '0', '5', '8'], 'values': ['52.69']}, {'key': ['000000000', '0', '5', '9'], 'values': ['50.99']}, {'key': ['000000000', '0', '5', '10'], 'values': ['51.99']}, {'key': ['000000000', '0', '5', '11'], 'values': ['53.82']}, {'key': ['000000000', '0', '6', '0'], 'values': ['54.91']}, {'key': ['000000000', '0', '6', '1'], 'values': ['55.93']}, {'key': ['000000000', '0', '6', '2'], 'values': ['56.44']}, {'key': ['000000000', '0', '6', '3'], 'values': ['56.42']}, {'key': ['000000000', '0', '6', '4'], 'values': ['56.06']}, {'key': ['000000000', '0', '6', '5'], 'values': ['55.96']}, {'key': ['000000000', '0', '6', '6'], 'values': ['55.85']}, {'key': ['000000000', '0', '6', '7'], 'values': ['55.56']}, {'key': ['000000000', '0', '6', '8'], 'values': ['55.51']}, {'key': ['000000000', '0', '6', '9'], 'values': ['55.28']}, {'key': ['000000000', '0', '6', '10'], 'values': ['54.64']}, {'key': ['000000000', '0', '6', '11'], 'values': ['54.38']}, {'key': ['000000000', '0', '7', '0'], 'values': ['54.14']}, {'key': ['000000000', '0', '7', '1'], 'values': ['53.46']}, {'key': ['000000000', '0', '7', '2'], 'values': ['52.25']}, {'key': ['000000000', '0', '7', '3'], 'values': ['50.54']}, {'key': ['000000000', '0', '7', '4'], 'values': ['49.45']}, {'key': ['000000000', '0', '7', '5'], 'values': ['48.47']}, {'key': ['000000000', '0', '7', '6'], 'values': ['47.60']}, {'key': ['000000000', '0', '7', '7'], 'values': ['46.51']}, {'key': ['000000000', '0', '7', '8'], 'values': ['46.50']}, {'key': ['000000000', '0', '7', '9'], 'values': ['46.49']}, {'key': ['000000000', '0', '7', '10'], 'values': ['46.80']}, {'key': ['000000000', '0', '7', '11'], 'values': ['48.25']}, {'key': ['000000000', '0', '8', '0'], 'values': ['50.05']}, {'key': ['000000000', '0', '8', '1'], 'values': ['52.21']}, {'key': ['000000000', '0', '8', '2'], 'values': ['54.89']}, {'key': ['000000000', '0', '8', '3'], 'values': ['58.07']}, ...]

In [7]:
# Open and parse the JSON file using standard python library

# Flatten the "students" array and include the parent "school" property
df = pd.json_normalize(
    json, record_path=["data"]
)

# Display the cleaned DataFrame
print(df)

NotImplementedError:

### Parse json

key:      [0, 2000, 0] --> [sector, year, month]

values:   rice stocks

--------------------------------------------------------------
example: ['sector': total rice stock, 'year': 2000, 'month': 2000]

values:  2210000 rice stock

### Prototype

In [18]:
test = pd.json_normalize(
    response.json(), record_path=["data"]
)

# Display the cleaned DataFrame
print(test)

                       key   values
0     [000000000, 0, 0, 0]  [44.77]
1     [000000000, 0, 0, 1]  [45.25]
2     [000000000, 0, 0, 2]  [45.79]
3     [000000000, 0, 0, 3]  [46.01]
4     [000000000, 0, 0, 4]  [46.32]
..                     ...      ...
211   [000000000, 1, 8, 7]      [.]
212   [000000000, 1, 8, 8]      [.]
213   [000000000, 1, 8, 9]      [.]
214  [000000000, 1, 8, 10]      [.]
215  [000000000, 1, 8, 11]      [.]

[216 rows x 2 columns]

> drop rows with ".. / Null" values

> make separate column using different key[sector] values

In [ ]:
test.to_csv("test.csv", index=True)

In [ ]:
test

                key        values
0      [0, 2000, 0]  [2364500.00]
1      [0, 2000, 1]  [2042300.00]
2      [0, 2000, 2]  [1765700.00]
3      [0, 2000, 3]  [1874900.00]
4      [0, 2000, 4]  [2067000.00]
...             ...           ...
1291   [3, 2026, 7]          [..]
1292   [3, 2026, 8]          [..]
1293   [3, 2026, 9]          [..]
1294  [3, 2026, 10]          [..]
1295  [3, 2026, 11]          [..]

[1296 rows x 2 columns]

In [ ]:
key_split = pd.DataFrame(test['key'].to_list(), index=test.index)
key_split.columns = ['sector', 'year', 'month']

In [ ]:
test = test.merge(key_split, on=test.index, how='left')

In [ ]:
test = test.drop(columns=['key_0', 'key'])

In [ ]:
test

            values sector  year month
0     [2364500.00]      0  2000     0
1     [2042300.00]      0  2000     1
2     [1765700.00]      0  2000     2
3     [1874900.00]      0  2000     3
4     [2067000.00]      0  2000     4
...            ...    ...   ...   ...
1291          [..]      3  2026     7
1292          [..]      3  2026     8
1293          [..]      3  2026     9
1294          [..]      3  2026    10
1295          [..]      3  2026    11

[1296 rows x 4 columns]

In [ ]:
total_stock = test.query("sector == '0'")
# total_stock.rename(columns={'values': 'total_stock'}, inplace=True)

commercial_stock = test.query("sector == '1'")
# commercial_stock.rename(columns={'values': 'stock_household'}, inplace=True)
# commerical_stock.drop(columns=['sector', 'year', 'month'])

household_stock = test.query("sector == '2'")
# household_stock.rename(columns={'values': 'stock_commercial'}, inplace=True)
# household_stock.drop(columns=['sector', 'year', 'month'])

nfa_stock = test.query("sector == '3'")
# nfa_stock.rename(columns={'values': 'stock_nfa'}, inplace=True)
# nfa_stock.drop(columns=['sector', 'year', 'month'])

           values sector  year month
972   [726600.00]      3  2000     0
973   [612200.00]      3  2000     1
974   [552500.00]      3  2000     2
975   [479300.00]      3  2000     3
976   [497900.00]      3  2000     4
...           ...    ...   ...   ...
1291         [..]      3  2026     7
1292         [..]      3  2026     8
1293         [..]      3  2026     9
1294         [..]      3  2026    10
1295         [..]      3  2026    11

[324 rows x 4 columns]